<script lang="ts">
  import { tick } from "svelte";
  import { TriangleAlert, X } from "lucide-svelte";
  import { corporateFade, corporateSlideFly } from "$lib/transitions";
  interface Props { title: string; consequence: string; confirmLabel: string; reasonRequired?: boolean; dependencyWarning?: string; destructive?: boolean; onConfirm: (reason: string) => void | Promise<void>; onCancel: () => void; }
  let { title, consequence, confirmLabel, reasonRequired = false, dependencyWarning, destructive = false, onConfirm, onCancel }: Props = $props();
  let reason = $state(""); let submitting = $state(false); let error = $state("");
  async function confirm() { if (reasonRequired && !reason.trim()) { error = "Enter a reason before continuing."; await tick(); return; } submitting = true; try { await onConfirm(reason.trim()); } finally { submitting = false; } }
</script>
<div class="dialog-backdrop corporate-dialog-backdrop backdrop-blur-corporate" role="presentation" transition:corporateFade={{ duration: 120 }}><div class="dialog corporate-dialog-surface backdrop-blur-corporate" role="dialog" aria-modal="true" aria-labelledby="dialog-title" transition:corporateSlideFly={{ duration: 180 }}><header><div class="icon"><TriangleAlert size={20}/></div><h2 id="dialog-title">{title}</h2><button type="button" aria-label="Cancel" onclick={onCancel}><X size={18}/></button></header><p>{consequence}</p>{#if dependencyWarning}<div class="warning"><strong>Connected records</strong><span>{dependencyWarning}</span></div>{/if}{#if reasonRequired}<label>Reason <span>Required</span><textarea bind:value={reason} rows="3" aria-invalid={Boolean(error)}></textarea></label>{#if error}<p class="error" role="alert">{error}</p>{/if}{/if}<footer><button type="button" onclick={onCancel}>Cancel</button><button type="button" class:destructive onclick={() => void confirm()} disabled={submitting}>{submitting ? "Working…" : confirmLabel}</button></footer></div></div>
<style>.dialog-backdrop{position:fixed;z-index:80;inset:0;display:grid;place-items:center;padding:18px}.dialog{width:min(500px,100%);border:1px solid var(--color-border-strong);border-radius:var(--radius-surface);padding:18px}header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px}.icon{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:var(--color-warning-soft);color:var(--color-warning-text)}h2,p{margin:0}h2{font-size:1.1rem}header button{display:grid;place-items:center;border:0;background:transparent;color:var(--color-muted)}.dialog>p{margin:13px 0;color:var(--color-muted);font-size:.875rem}.warning{display:grid;gap:3px;margin:12px 0;border-left:3px solid var(--color-warning);background:var(--color-warning-soft);padding:9px 11px}.warning span{color:var(--color-muted);font-size:.8rem}label{display:grid;gap:5px;font-size:.8rem;font-weight:700}label>span{color:var(--color-danger);font-size:.7rem}textarea{border:1px solid var(--color-field-border);border-radius:var(--radius-control);background:var(--color-field-bg);padding:9px}.error{color:var(--color-danger)!important}footer{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}footer button{min-height:38px;border:1px solid var(--color-border-strong);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-text);font-weight:700;padding:0 13px}.destructive{border-color:var(--color-danger)!important;background:var(--color-danger)!important;color:white!important}</style>
