<script lang="ts">
  import { onMount } from "svelte";
  import { FileCheck2, Search, TriangleAlert } from "lucide-svelte";
  import EmptyState from "$lib/components/feedback/EmptyState.svelte";
  import ErrorState from "$lib/components/feedback/ErrorState.svelte";
  import { getBrowserDatabase } from "$lib/data/database";
  import { ChemicalProductRepository, SdsRevisionRepository, SiteChemicalInventoryRepository } from "$lib/data/repositories/chemical";
  import type { ChemicalProduct, SdsRevision, SiteChemicalInventory } from "$lib/domain/chemical";
  import { workspaceScope } from "$lib/workspace/scope";

  let products = $state<ChemicalProduct[]>([]);
  let revisions = $state<SdsRevision[]>([]);
  let inventory = $state<SiteChemicalInventory[]>([]);
  let query = $state("");
  let filter = $state<"all" | "attention" | "current" | "unavailable">("attention");
  let loading = $state(true);
  let error = $state<string | null>(null);
  const scopedProductIds = $derived(new Set(inventory.filter((item) => !$workspaceScope.siteId || item.siteId === $workspaceScope.siteId).map((item) => item.productId)));
  const rows = $derived(products.filter((product) => (!$workspaceScope.siteId || scopedProductIds.has(product.id)) && `${product.productName} ${product.productCode ?? ""} ${product.businessId}`.toLowerCase().includes(query.toLowerCase())).map((product) => ({ product, history: revisions.filter((item) => item.productId === product.id).sort((a,b) => (b.revisionDate ?? "").localeCompare(a.revisionDate ?? "")), current: revisions.find((item) => item.productId === product.id && item.currentStatus === "Current") })).filter((row) => filter === "all" || (filter === "attention" && (!row.current || row.current.reviewStatus !== "Accepted")) || (filter === "current" && row.current?.reviewStatus === "Accepted") || (filter === "unavailable" && (!row.current || row.history.some((item) => item.currentStatus === "Unavailable")))));

  onMount(() => { void load(); });
  async function load() { loading = true; error = null; try { const adapter = await getBrowserDatabase(); [products, revisions, inventory] = await Promise.all([new ChemicalProductRepository(adapter.database).list({ includeArchived: true }), new SdsRevisionRepository(adapter.database).list({ includeArchived: true }), new SiteChemicalInventoryRepository(adapter.database).list({ includeArchived: true })]); } catch (cause) { error = cause instanceof Error ? cause.message : String(cause); } finally { loading = false; } }
  function reviewState(row: (typeof rows)[number]) { if (!row.current) return { label: "SDS unavailable", tone: "critical" }; if (row.current.reviewStatus === "Accepted") return { label: "Accepted", tone: "positive" }; return { label: row.current.reviewStatus, tone: "warning" }; }
</script>

<section class="sds-page" aria-labelledby="sds-title"><header><div><span>Chemicals</span><h1 id="sds-title">SDS Review</h1><p>Review safety data sheets in Product context without losing the connection to Sites where each Product is present.</p></div><a href="/master/products">Open Products</a></header>
  {#if loading}<p role="status">Loading SDS review queue…</p>{:else if error}<ErrorState message={error} onRetry={() => void load()}/>{:else}
    <div class="toolbar"><label><Search size={16}/><span class="visually-hidden">Search Products</span><input bind:value={query} placeholder="Search Product or code"/></label><div class="filters" aria-label="SDS review filter">{#each [{id:"attention",label:"Needs attention"},{id:"current",label:"Accepted"},{id:"unavailable",label:"Unavailable"},{id:"all",label:"All"}] as option}<button type="button" class:active={filter===option.id} aria-pressed={filter===option.id} onclick={() => (filter=option.id as typeof filter)}>{option.label}</button>{/each}</div></div>
    <div class="summary"><div><strong>{rows.filter((row) => !row.current).length}</strong><span>Products without a current SDS</span></div><div><strong>{rows.filter((row) => row.current && row.current.reviewStatus !== "Accepted").length}</strong><span>Current SDS records awaiting acceptance</span></div><div><strong>{rows.filter((row) => row.current?.reviewStatus === "Accepted").length}</strong><span>Accepted current SDS records</span></div></div>
    {#if rows.length}<div class="review-list">{#each rows as row}{@const status = reviewState(row)}<article><div class={`status-icon ${status.tone}`}>{status.tone === "positive" ? "✓" : "!"}</div><div class="product"><a href={`/master/products/${row.product.id}`}>{row.product.productName}</a><span>{row.product.productCode ?? row.product.businessId} · {row.product.formulationType} · {row.product.physicalState}</span></div><div class="revision"><span>Current SDS</span><strong>{row.current?.revisionDate ?? (row.current?.revisionDateUnknown ? "Date unknown" : "Not available")}</strong><small>{row.current?.language ?? "—"} · {row.current?.jurisdiction ?? "—"}</small></div><div class={`review-state ${status.tone}`}><strong>{status.label}</strong><small>{row.history.length} revision{row.history.length === 1 ? "" : "s"}</small></div><a class="open" href={row.current ? `/master/products/${row.product.id}/sds/${row.current.id}` : `/master/products/${row.product.id}/sds/new`}>{row.current ? "Review" : "Add SDS"}</a></article>{/each}</div>{:else}<EmptyState title="No SDS records match" message="Change the current scope, search, or review filter."/>{/if}
  {/if}
</section>

<style>
  .sds-page { width: min(100%, 1440px); min-height: 100%; margin: 0 auto; padding: 28px 30px 40px; } header { display: flex; align-items: flex-end; justify-content: space-between; gap: 18px; margin-bottom: 18px; } header div { display: grid; gap: 5px; } header span { color: var(--color-action); font-size: .7rem; font-weight: 750; text-transform: uppercase; } h1,p { margin: 0; } h1 { font-size: 1.8rem; } header p { max-width: 700px; color: var(--color-muted); font-size: .875rem; } header>a { border: 1px solid var(--color-border-strong); border-radius: var(--radius-control); color: var(--color-text); font-size: .8rem; font-weight: 700; padding: 8px 11px; text-decoration: none; }
  .toolbar { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 12px; } .toolbar>label { display: grid; grid-template-columns: auto 1fr; align-items: center; gap: 7px; min-width: min(100%, 360px); border: 1px solid var(--color-border); border-radius: var(--radius-control); background: var(--color-surface); color: var(--color-muted); padding: 0 9px; } input { min-height: 38px; border: 0; background: transparent; outline: 0; } .filters { display: flex; gap: 3px; border: 1px solid var(--color-border); border-radius: var(--radius-control); background: var(--color-surface); padding: 3px; } .filters button { min-height: 31px; border: 0; border-radius: 4px; background: transparent; color: var(--color-muted); font-size: .72rem; font-weight: 700; padding: 0 8px; } .filters button.active { background: var(--color-accent-soft); color: var(--color-action); }
  .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 9px; margin-bottom: 12px; } .summary div { display: grid; gap: 2px; border: 1px solid var(--color-border); border-radius: var(--radius-surface); background: var(--color-surface); padding: 12px; } .summary strong { font-size: 1.4rem; } .summary span { color: var(--color-muted); font-size: .72rem; }
  .review-list { border: 1px solid var(--color-border); border-radius: var(--radius-surface); background: var(--color-surface); } article { display: grid; grid-template-columns: auto minmax(220px, 1.3fr) minmax(150px, .8fr) minmax(130px, .6fr) auto; align-items: center; gap: 12px; border-bottom: 1px solid var(--color-border); padding: 12px 14px; } article:last-child { border-bottom: 0; } .status-icon { display: grid; place-items: center; width: 30px; height: 30px; border-radius: 50%; background: var(--color-warning-soft); color: var(--color-warning-text); font-weight: 800; } .status-icon.critical { background: var(--color-danger-soft); color: var(--color-danger); } .status-icon.positive { background: var(--color-positive-soft); color: var(--color-positive-text); }
  .product, .revision, .review-state { display: grid; gap: 2px; } .product a { color: var(--color-text); font-size: .85rem; font-weight: 750; text-decoration: none; } .product span, .revision span, small { color: var(--color-muted); font-size: .68rem; } .revision strong, .review-state strong { font-size: .77rem; } .review-state.warning { color: var(--color-warning-text); } .review-state.critical { color: var(--color-danger); } .review-state.positive { color: var(--color-positive-text); }
  .open { border: 1px solid var(--color-action); border-radius: var(--radius-control); color: var(--color-action); font-size: .72rem; font-weight: 750; padding: 6px 9px; text-decoration: none; }
  .visually-hidden { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); }
  @media (max-width: 900px) { article { grid-template-columns: auto 1fr auto; } .revision, .review-state { grid-column: 2; } .open { grid-column: 3; grid-row: 1; } }
  @media (max-width: 680px) { .sds-page { padding: 20px 15px 30px; } header, .toolbar { align-items: stretch; flex-direction: column; } .filters { overflow-x: auto; } .summary { grid-template-columns: 1fr; } }
</style>
