<script lang="ts">
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";
  import { Save } from "lucide-svelte";
  import { ChemicalApplication } from "$lib/application/chemical";
  import { foundationApplication } from "$lib/application/foundation";
  import ConfirmationDialog from "$lib/components/feedback/ConfirmationDialog.svelte";
  import EmptyState from "$lib/components/feedback/EmptyState.svelte";
  import ErrorState from "$lib/components/feedback/ErrorState.svelte";
  import SaveState from "$lib/components/feedback/SaveState.svelte";
  import FormStep from "$lib/components/forms/FormStep.svelte";
  import FunctionPicker from "$lib/components/forms/FunctionPicker.svelte";
  import GuidedForm from "$lib/components/forms/GuidedForm.svelte";
  import InlineValidation from "$lib/components/forms/InlineValidation.svelte";
  import LocationPicker from "$lib/components/forms/LocationPicker.svelte";
  import ProcessPicker from "$lib/components/forms/ProcessPicker.svelte";
  import RelationshipPicker from "$lib/components/forms/RelationshipPicker.svelte";
  import ReviewBeforeSave from "$lib/components/forms/ReviewBeforeSave.svelte";
  import TaskPicker from "$lib/components/forms/TaskPicker.svelte";
  import CompletenessPanel from "$lib/components/workspace/CompletenessPanel.svelte";
  import ConnectedRecords from "$lib/components/workspace/ConnectedRecords.svelte";
  import RecordWorkspace from "$lib/components/workspace/RecordWorkspace.svelte";
  import RevisionTimeline from "$lib/components/workspace/RevisionTimeline.svelte";
  import { getBrowserDatabase, type RecordRevision } from "$lib/data/database";
  import { RevisionRepository } from "$lib/data/revisions";
  import { APPLICATION_METHODS, CHEMICAL_OPERATING_CONDITIONS, CHEMICAL_USE_FREQUENCIES, DURATION_UNITS, QUANTITY_SCALES, type ChemicalProduct, type ChemicalUse } from "$lib/domain/chemical";
  import type { Location } from "$lib/domain/location";
  import { assignmentIsEffective, type LocationFunctionAssignment, type OperationalFunction, type Process, type Task } from "$lib/domain/operations";
  import type { AppRoute } from "$lib/navigation/route-registry";
  import { rememberRecentRecord } from "$lib/workspace/recent-records";
  import { workspaceScope } from "$lib/workspace/scope";

  interface Props{route:AppRoute;}let{route}:Props=$props();
  let application=$state<ChemicalApplication|null>(null);let products=$state<ChemicalProduct[]>([]);let locations=$state<Location[]>([]);let functions=$state<OperationalFunction[]>([]);let assignments=$state<LocationFunctionAssignment[]>([]);let processes=$state<Process[]>([]);let tasks=$state<Task[]>([]);let useRecord=$state<ChemicalUse>();let revisions=$state<RecordRevision<ChemicalUse>[]>([]);let loading=$state(true);let saving=$state(false);let error=$state<string|null>(null);let activeIndex=$state(0);let detailTab=$state("overview");let archiveOpen=$state(false);
  let form=$state({productId:"",siteId:"",locationId:"",operationalFunctionId:"",processId:"",taskId:"",operatingCondition:"Routine",frequency:"Unknown",duration:"",durationUnit:"Unknown",quantityScale:"Unknown",applicationMethod:"Unknown",deferredControlNotes:"",notes:""});
  const sites=$derived(locations.filter((item)=>item.nodeType==="Site"&&item.lifecycleStatus==="active"));const locationOptions=$derived(locations.filter((item)=>form.siteId&&(item.id===form.siteId||item.resolvedSiteId===form.siteId)&&item.lifecycleStatus==="active"));const functionOptions=$derived(functions.filter((fn)=>fn.lifecycleStatus==="active"&&fn.status==="Active"&&assignments.some((item)=>item.locationId===form.locationId&&item.operationalFunctionId===fn.id&&assignmentIsEffective(item))));const processOptions=$derived(processes.filter((item)=>item.lifecycleStatus==="active"&&item.resolvedSiteId===form.siteId&&item.operationalFunctionId===form.operationalFunctionId));const taskOptions=$derived(tasks.filter((item)=>item.lifecycleStatus==="active"&&item.processId===form.processId&&item.resolvedSiteId===form.siteId));const selectedProduct=$derived(products.find((item)=>item.id===form.productId));const selectedSite=$derived(locations.find((item)=>item.id===form.siteId));const selectedLocation=$derived(locations.find((item)=>item.id===form.locationId));const selectedFunction=$derived(functions.find((item)=>item.id===form.operationalFunctionId));const selectedProcess=$derived(processes.find((item)=>item.id===form.processId));const selectedTask=$derived(tasks.find((item)=>item.id===form.taskId));
  const steps=[{id:"product",label:"Product",description:"Choose the material"},{id:"context",label:"Work context",description:"Place, Function, Process, Task"},{id:"conditions",label:"Conditions",description:"Frequency, duration, method"},{id:"controls",label:"Controls & evidence",description:"Safeguards and notes"},{id:"review",label:"Review",description:"Confirm the relationship"}];
  onMount(()=>{void load();});$effect(()=>{if(useRecord)rememberRecentRecord({path:`/master/chemical-uses/${useRecord.id}`,title:selectedProduct?.productName??useRecord.businessId,context:"Chemical Use"});});
  async function load(){loading=true;error=null;try{const adapter=await getBrowserDatabase();const app=new ChemicalApplication(adapter.database);application=app;const services=await foundationApplication.services();[products,locations,functions,assignments,processes,tasks]=await Promise.all([app.repositories.products.list({includeArchived:true}),services.locations.list(true),services.operationalFunctions.list(true),services.locationFunctionAssignments.list(true),services.processes.list(true),services.tasks.list(true)]);if(route.recordId){useRecord=await app.repositories.uses.get(route.recordId,{includeArchived:true});form={productId:useRecord.productId,siteId:useRecord.siteId,locationId:useRecord.locationId,operationalFunctionId:useRecord.operationalFunctionId,processId:useRecord.processId,taskId:useRecord.taskId??"",operatingCondition:useRecord.operatingCondition,frequency:useRecord.frequency,duration:useRecord.duration?.toString()??"",durationUnit:useRecord.durationUnit,quantityScale:useRecord.quantityScale,applicationMethod:useRecord.applicationMethod,deferredControlNotes:useRecord.deferredControlNotes,notes:useRecord.notes};revisions=await new RevisionRepository(adapter.database).listForRecord<ChemicalUse>("ChemicalUse",useRecord.id);}else{form.siteId=$workspaceScope.siteId??"";form.locationId=$workspaceScope.locationId??"";form.operationalFunctionId=$workspaceScope.operationalFunctionId??"";const candidates=processes.filter((item)=>(!form.siteId||item.resolvedSiteId===form.siteId)&&(!form.operationalFunctionId||item.operationalFunctionId===form.operationalFunctionId));if(candidates.length===1)form.processId=candidates[0].id;}}catch(cause){error=cause instanceof Error?cause.message:String(cause);}finally{loading=false;}}
  function resetAfter(name:"site"|"location"|"function"|"process"){if(name==="site"){form.locationId="";form.operationalFunctionId="";}if(name==="site"||name==="location")form.operationalFunctionId="";if(name!=="process")form.processId="";form.taskId="";}function numberValue(value:string){return value.trim()?Number(value):undefined;}
  function validateStep(){if(activeIndex===0&&!form.productId)return"Select the Product being used.";if(activeIndex===1){if(!form.siteId)return"Select a Site.";if(!form.locationId)return"Select the physical Location.";if(!form.operationalFunctionId)return"Select a Function assigned at that Location.";if(!form.processId)return"Select a Process in that Function.";}if(activeIndex===2&&form.duration&&!form.durationUnit)return"Select a duration unit.";return"";}
  function next(){const message=validateStep();if(message){error=message;return;}error=null;activeIndex=Math.min(4,activeIndex+1);}
  async function save(){if(!application)return;error=null;saving=true;try{const input={productId:form.productId,siteId:form.siteId,locationId:form.locationId,operationalFunctionId:form.operationalFunctionId,processId:form.processId,taskId:form.taskId||undefined,operatingCondition:form.operatingCondition as ChemicalUse["operatingCondition"],frequency:form.frequency as ChemicalUse["frequency"],duration:numberValue(form.duration),durationUnit:form.durationUnit as ChemicalUse["durationUnit"],quantityScale:form.quantityScale as ChemicalUse["quantityScale"],applicationMethod:form.applicationMethod as ChemicalUse["applicationMethod"],controlIds:useRecord?.controlIds??[],evidenceReferenceIds:useRecord?.evidenceReferenceIds??[],deferredControlNotes:form.deferredControlNotes,notes:form.notes,status:"Active" as const};const saved=useRecord?await application.uses.update(useRecord.id,input,useRecord.revision):await application.uses.create(input);await goto(`/master/chemical-uses/${saved.id}`);}catch(cause){error=cause instanceof Error?cause.message:String(cause);}finally{saving=false;}}
  async function archive(reason:string){if(!application||!useRecord)return;await application.uses.archive(useRecord.id,useRecord.revision,reason);archiveOpen=false;await load();}async function restore(){if(!application||!useRecord)return;await application.uses.restore(useRecord.id,useRecord.revision);await load();}
  const sentence=$derived(`${selectedProduct?.productName??"This Product"} is ${form.applicationMethod.toLowerCase()} during ${form.operatingCondition.toLowerCase()} work at ${selectedLocation?.name??"an unspecified Location"}, within the ${selectedFunction?.name??"unspecified"} Function and ${selectedProcess?.name??"unspecified"} Process${selectedTask?`, during ${selectedTask.name}`:""}.`);
</script>

{#if loading}<section class="use-page" role="status">Loading Chemical Use workspace…</section>{:else if route.mode==="detail"&&(error||!useRecord)}<section class="use-page"><ErrorState message={error??"Chemical Use not found"} onRetry={()=>void load()}/></section>{:else if route.mode==="detail"&&useRecord&&selectedProduct}
<RecordWorkspace title={selectedProduct.productName} recordType="Chemical Use" summary={sentence} contextPath={[{label:"Chemical Uses",href:"/master/chemical-uses"},{label:selectedSite?.name??"Site",href:selectedSite?`/operations/locations/${selectedSite.id}`:undefined},{label:selectedFunction?.name??"Function",href:selectedFunction?`/enterprise/functions/${selectedFunction.id}`:undefined},{label:selectedProcess?.name??"Process",href:selectedProcess?`/operations/processes/${selectedProcess.id}`:undefined}]} statuses={[{label:"Lifecycle",value:useRecord.lifecycleStatus==="archived"?"Archived":useRecord.status,tone:useRecord.lifecycleStatus==="active"?"positive":"neutral"},{label:"Review",value:"Draft",tone:"warning"},{label:"Data quality",value:useRecord.status==="Needs Verification"?"Needs verification":"Verified",tone:useRecord.status==="Needs Verification"?"warning":"positive"},{label:"Sync / exchange",value:useRecord.lastExchangePackageId?"Exchanged":"Local changes",tone:"information"}]} actions={[{label:"Edit",onSelect:()=>void goto(`/master/chemical-uses/${useRecord!.id}/edit`),primary:true},{label:"Open Product",onSelect:()=>void goto(`/master/products/${useRecord!.productId}`)}]} moreActions={useRecord.lifecycleStatus==="archived"?[{label:"Restore",onSelect:()=>void restore()}]:[{label:"Archive…",onSelect:()=>archiveOpen=true}]} tabs={[{id:"overview",label:"Overview"},{id:"controls",label:"Controls"},{id:"evidence",label:"Evidence"},{id:"history",label:"History"}]} activeTab={detailTab} onTabChange={(id)=>detailTab=id}>
  {#if detailTab==="overview"}
  <div class="relationship-sentence">{sentence}</div><div class="use-overview"><section><h2>Work context</h2><dl><div><dt>Product</dt><dd><a href={`/master/products/${useRecord.productId}`}>{selectedProduct.productName}</a></dd></div><div><dt>Site</dt><dd>{selectedSite?.name}</dd></div><div><dt>Location</dt><dd>{selectedLocation?.name}</dd></div><div><dt>Function</dt><dd>{selectedFunction?.name}</dd></div><div><dt>Process</dt><dd>{selectedProcess?.name}</dd></div><div><dt>Task</dt><dd>{selectedTask?.name??"No specific Task"}</dd></div><div><dt>Operating condition</dt><dd>{useRecord.operatingCondition}</dd></div><div><dt>Frequency / duration</dt><dd>{useRecord.frequency} · {useRecord.duration??"Unknown"} {useRecord.durationUnit}</dd></div><div><dt>Method / scale</dt><dd>{useRecord.applicationMethod} · {useRecord.quantityScale}</dd></div></dl></section><div><CompletenessPanel rules={[{label:"Product",complete:Boolean(useRecord.productId)},{label:"Site and Location",complete:Boolean(useRecord.siteId&&useRecord.locationId)},{label:"Operational Function",complete:Boolean(useRecord.operationalFunctionId)},{label:"Process",complete:Boolean(useRecord.processId)},{label:"Task disposition",complete:Boolean(useRecord.taskId),guidance:"Link a Task when the use occurs during a specific reusable work step."},{label:"Operating condition",complete:useRecord.operatingCondition!=="Unknown"},{label:"Duration",complete:Boolean(useRecord.duration),guidance:"Document a duration when known."},{label:"Controls or deferred rationale",complete:useRecord.controlIds.length>0||Boolean(useRecord.deferredControlNotes),guidance:"Link controls or explain why they are deferred."}]}/><ConnectedRecords records={[{label:"Product",value:selectedProduct.productName,href:`/master/products/${selectedProduct.id}`},{label:"Location",value:selectedLocation?.name??"Unknown",href:selectedLocation?`/operations/locations/${selectedLocation.id}`:undefined},{label:"Function",value:selectedFunction?.name??"Unknown",href:selectedFunction?`/enterprise/functions/${selectedFunction.id}`:undefined},{label:"Process",value:selectedProcess?.name??"Unknown",href:selectedProcess?`/operations/processes/${selectedProcess.id}`:undefined},{label:"Task",value:selectedTask?.name??"Not assigned",href:selectedTask?`/operations/tasks/${selectedTask.id}`:undefined},{label:"Controls",value:useRecord.controlIds.length},{label:"Evidence",value:useRecord.evidenceReferenceIds.length}]}/></div></div>
  {:else if detailTab==="controls"}
    {#if useRecord.controlIds.length}<ConnectedRecords title="Linked Controls" records={useRecord.controlIds.map((_,index)=>({label:`Control ${index+1}`,value:"Linked governed control"}))}/>{:else}<EmptyState title="No structured Controls linked" message={useRecord.deferredControlNotes||"Document current safeguards or explain why structured control linking is deferred."}/>{/if}
  {:else if detailTab==="evidence"}
    {#if useRecord.evidenceReferenceIds.length}<ConnectedRecords title="Linked Evidence" records={useRecord.evidenceReferenceIds.map((_,index)=>({label:`Evidence ${index+1}`,value:"Linked evidence reference"}))}/>{:else}<EmptyState title="No structured Evidence linked" message={useRecord.notes||"Link supporting observations, procedures, interviews, or other evidence."}/>{/if}
  {:else}
    <RevisionTimeline revisions={revisions.map((item)=>({id:item.id,revision:item.revision,operation:item.operation,changedAt:item.changedAt,changedBy:item.changedBy}))}/>
  {/if}
</RecordWorkspace>
{:else}
<section class="use-page"><header><span>Chemicals</span><h1>{useRecord?"Edit Chemical Use":"Document Chemical Use"}</h1><p>Build one connected statement from Product through work context, conditions, controls, and evidence.</p></header><GuidedForm title="Chemical Use" {steps} {activeIndex} onStepSelect={(index)=>{if(index<=activeIndex)activeIndex=index;}}>{#if error}<InlineValidation message={error} tone="error"/>{/if}
  {#if activeIndex===0}<FormStep title="Which Product is being used?" prompt="Choose the commercial Product identity. Inventory presence alone does not create a Chemical Use."><RelationshipPicker label="Product" value={form.productId} options={products.filter((item)=>item.lifecycleStatus==="active").map((item)=>({value:item.id,label:item.productName,description:item.formulationType}))} required onChange={(value)=>form.productId=value}/></FormStep>
  {:else if activeIndex===1}<FormStep title="Where and during what work?" prompt="Each choice filters the relationships that can follow."><RelationshipPicker label="Site" value={form.siteId} options={sites.map((item)=>({value:item.id,label:item.name}))} required onChange={(value)=>{form.siteId=value;resetAfter("site");}}/><LocationPicker value={form.locationId} options={locationOptions.map((item)=>({value:item.id,label:item.name,description:item.nodeType}))} required disabled={!form.siteId} onChange={(value)=>{form.locationId=value;resetAfter("location");}}/><FunctionPicker value={form.operationalFunctionId} options={functionOptions.map((item)=>({value:item.id,label:item.name,description:item.functionCategory}))} required disabled={!form.locationId} onChange={(value)=>{form.operationalFunctionId=value;resetAfter("function");}}/><ProcessPicker value={form.processId} options={processOptions.map((item)=>({value:item.id,label:item.name,description:item.processType}))} required onChange={(value)=>{form.processId=value;resetAfter("process");}}/><TaskPicker value={form.taskId} options={taskOptions.map((item)=>({value:item.id,label:item.name,description:item.routineClassification}))} onChange={(value)=>form.taskId=value}/></FormStep>
  {:else if activeIndex===2}<FormStep title="What conditions describe this use?" prompt="Operating condition belongs to this Chemical Use, not to the reusable Task."><RelationshipPicker label="Operating condition" value={form.operatingCondition} options={CHEMICAL_OPERATING_CONDITIONS.map((value)=>({value,label:value}))} required onChange={(value)=>form.operatingCondition=value}/><RelationshipPicker label="Frequency" value={form.frequency} options={CHEMICAL_USE_FREQUENCIES.map((value)=>({value,label:value}))} required onChange={(value)=>form.frequency=value}/><div class="field-grid"><label>Duration<input type="number" min="0" step="any" bind:value={form.duration}/></label><RelationshipPicker label="Duration unit" value={form.durationUnit} options={DURATION_UNITS.map((value)=>({value,label:value}))} onChange={(value)=>form.durationUnit=value}/></div><RelationshipPicker label="Application method" value={form.applicationMethod} options={APPLICATION_METHODS.map((value)=>({value,label:value}))} required onChange={(value)=>form.applicationMethod=value}/><RelationshipPicker label="Quantity scale" value={form.quantityScale} options={QUANTITY_SCALES.map((value)=>({value,label:value}))} required onChange={(value)=>form.quantityScale=value}/></FormStep>
  {:else if activeIndex===3}<FormStep title="What controls and evidence support this record?" prompt="Existing linked controls and evidence are preserved when editing."><label class="text-field">Controls or deferred rationale<textarea rows="4" bind:value={form.deferredControlNotes}></textarea><small>Explain current safeguards or why structured control linking is deferred.</small></label><label class="text-field">Evidence and notes<textarea rows="4" bind:value={form.notes}></textarea><small>Describe the observation, interview, procedure, or other supporting evidence.</small></label></FormStep>
  {:else}<ReviewBeforeSave {sentence} items={[{label:"Product",value:selectedProduct?.productName??"",attention:!selectedProduct},{label:"Site",value:selectedSite?.name??"",attention:!selectedSite},{label:"Location",value:selectedLocation?.name??"",attention:!selectedLocation},{label:"Function",value:selectedFunction?.name??"",attention:!selectedFunction},{label:"Process",value:selectedProcess?.name??"",attention:!selectedProcess},{label:"Task",value:selectedTask?.name??"No specific Task"},{label:"Operating condition",value:form.operatingCondition},{label:"Frequency",value:form.frequency},{label:"Application method",value:form.applicationMethod}]}/>{/if}
  <footer><button type="button" class="secondary" onclick={()=>void goto(useRecord?`/master/chemical-uses/${useRecord.id}`:"/master/chemical-uses")}>Cancel</button><span><SaveState state={saving?"saving":"unsaved"}/></span>{#if activeIndex>0}<button type="button" class="secondary" onclick={()=>activeIndex--}>Back</button>{/if}{#if activeIndex<4}<button type="button" class="primary" onclick={next}>Continue</button>{:else}<button type="button" class="primary" disabled={saving} onclick={()=>void save()}><Save size={16}/>{saving?"Saving…":useRecord?"Save changes":"Save Chemical Use"}</button>{/if}</footer>
</GuidedForm></section>
{/if}
{#if archiveOpen&&useRecord}<ConfirmationDialog title="Archive this Chemical Use?" consequence="The record will stop appearing in active work, but its Product, Location, Function, Process, Task, controls, evidence, and revision history remain connected." confirmLabel="Archive Chemical Use" reasonRequired destructive onConfirm={archive} onCancel={()=>archiveOpen=false}/>{/if}

<style>.use-page{width:min(100%,1120px);margin:0 auto;padding:28px 30px 40px}.use-page>header{display:grid;gap:5px;margin-bottom:17px}.use-page>header span{color:var(--color-action);font-size:.7rem;font-weight:750;text-transform:uppercase}h1,h2,p{margin:0}h1{font-size:1.8rem}.use-page>header p{color:var(--color-muted);font-size:.85rem}.relationship-sentence{margin-bottom:14px;border-left:3px solid var(--color-action);border-radius:0 var(--radius-control) var(--radius-control) 0;background:var(--color-accent-soft);font-size:.95rem;font-weight:650;padding:12px 14px}.use-overview{display:grid;grid-template-columns:minmax(320px,1.1fr) minmax(280px,.9fr);gap:14px}.use-overview>section{overflow:hidden;border:1px solid var(--color-border);border-radius:var(--radius-surface);background:var(--color-surface)}.use-overview h2{border-bottom:1px solid var(--color-border);font-size:.9rem;padding:12px 14px}.use-overview dl{display:grid;margin:0}.use-overview dl div{display:grid;grid-template-columns:minmax(130px,.7fr)1.3fr;gap:9px;border-bottom:1px solid var(--color-border);padding:9px 14px}.use-overview dt{color:var(--color-muted);font-size:.75rem}.use-overview dd{margin:0;font-size:.78rem;font-weight:650}.use-overview>div{display:grid;gap:12px}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field-grid>label,.text-field{display:grid;gap:5px;font-size:.82rem;font-weight:720}.field-grid input,.text-field textarea{border:1px solid var(--color-field-border);border-radius:var(--radius-control);background:var(--color-field-bg);padding:9px 10px}.text-field small{color:var(--color-muted);font-size:.72rem;font-weight:500}footer{display:flex;align-items:center;gap:8px;margin-top:22px;border-top:1px solid var(--color-border);padding-top:14px}footer>span{flex:1}footer button{display:inline-flex;align-items:center;gap:6px;min-height:38px;border:1px solid var(--color-border-strong);border-radius:var(--radius-control);background:var(--color-surface);font-weight:700;padding:0 13px}footer .primary{border-color:var(--color-action);background:var(--color-action);color:white}@media(max-width:760px){.use-page{padding:20px 15px 30px}.use-overview,.field-grid{grid-template-columns:1fr}}</style>
