<script lang="ts">
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";
  import { FlaskConical, PackagePlus } from "lucide-svelte";
  import { ChemicalApplication } from "$lib/application/chemical";
  import { foundationApplication } from "$lib/application/foundation";
  import ConfirmationDialog from "$lib/components/feedback/ConfirmationDialog.svelte";
  import EmptyState from "$lib/components/feedback/EmptyState.svelte";
  import ErrorState from "$lib/components/feedback/ErrorState.svelte";
  import CompletenessPanel from "$lib/components/workspace/CompletenessPanel.svelte";
  import ConnectedRecords from "$lib/components/workspace/ConnectedRecords.svelte";
  import RecordWorkspace from "$lib/components/workspace/RecordWorkspace.svelte";
  import RelationshipList from "$lib/components/workspace/RelationshipList.svelte";
  import RevisionTimeline from "$lib/components/workspace/RevisionTimeline.svelte";
  import SummaryCard from "$lib/components/workspace/SummaryCard.svelte";
  import { getBrowserDatabase, type RecordRevision } from "$lib/data/database";
  import { RevisionRepository } from "$lib/data/revisions";
  import type { ChemicalProduct, ChemicalSubstance, ChemicalUse, ProductSubstance, SdsRevision, SiteChemicalInventory } from "$lib/domain/chemical";
  import type { Organization } from "$lib/domain/enterprise";
  import type { Location } from "$lib/domain/location";
  import type { OperationalFunction, Process, Task } from "$lib/domain/operations";
  import type { AppRoute } from "$lib/navigation/route-registry";
  import { rememberRecentRecord } from "$lib/workspace/recent-records";
  import { setWorkspaceScope } from "$lib/workspace/scope";

  interface Props { route: AppRoute; }
  let { route }: Props = $props();
  let application=$state<ChemicalApplication|null>(null);let product=$state<ChemicalProduct>();let substances=$state<ChemicalSubstance[]>([]);let composition=$state<ProductSubstance[]>([]);let sds=$state<SdsRevision[]>([]);let inventory=$state<SiteChemicalInventory[]>([]);let uses=$state<ChemicalUse[]>([]);let organizations=$state<Organization[]>([]);let locations=$state<Location[]>([]);let functions=$state<OperationalFunction[]>([]);let processes=$state<Process[]>([]);let tasks=$state<Task[]>([]);let revisions=$state<RecordRevision<ChemicalProduct>[]>([]);let loading=$state(true);let error=$state<string|null>(null);let activeTab=$state("overview");let archiveOpen=$state(false);
  const productId=$derived(product?.id??"");const manufacturerId=$derived(product?.manufacturerOrganizationId);const productComposition=$derived(composition.filter((item)=>item.productId===productId));const productSds=$derived(sds.filter((item)=>item.productId===productId).sort((a,b)=>(b.revisionDate??"").localeCompare(a.revisionDate??"")));const currentSds=$derived(productSds.find((item)=>item.currentStatus==="Current"));const productInventory=$derived(inventory.filter((item)=>item.productId===productId));const productUses=$derived(uses.filter((item)=>item.productId===productId));const sites=$derived([...new Set([...productInventory.map((item)=>item.siteId),...productUses.map((item)=>item.siteId)])].map((id)=>locations.find((item)=>item.id===id)).filter((item):item is Location=>Boolean(item)));const manufacturer=$derived(manufacturerId?organizations.find((item)=>item.id===manufacturerId):undefined);
  const completeness=$derived(product?[{label:"Product identity",complete:Boolean(product.productName&&product.businessId)},{label:"Manufacturer disposition",complete:Boolean(product.manufacturerOrganizationId||product.manufacturerUnknown),guidance:"Select a manufacturer or mark it explicitly unknown."},{label:"Formulation type",complete:product.formulationType!=="Unknown"},{label:"Physical state",complete:product.physicalState!=="Unknown"},{label:"Current SDS",complete:Boolean(currentSds),guidance:"Add or promote the current SDS revision."},{label:"Composition",complete:productComposition.length>0,guidance:"Link at least one disclosed component or record the composition evidence."}]:[]);
  onMount(()=>{void load();});$effect(()=>{if(product)rememberRecentRecord({path:`/master/products/${product.id}`,title:product.productName,context:"Chemical Product"});});
  async function load(){loading=true;error=null;try{const adapter=await getBrowserDatabase();const app=new ChemicalApplication(adapter.database);application=app;const services=await foundationApplication.services();[product,substances,composition,sds,inventory,uses,organizations,locations,functions,processes,tasks,revisions]=await Promise.all([app.repositories.products.get(route.recordId??"",{includeArchived:true}),app.repositories.substances.list({includeArchived:true}),app.repositories.composition.list({includeArchived:true}),app.repositories.sds.list({includeArchived:true}),app.repositories.inventory.list({includeArchived:true}),app.repositories.uses.list({includeArchived:true}),services.organizations.list(true),services.locations.list(true),services.operationalFunctions.list(true),services.processes.list(true),services.tasks.list(true),new RevisionRepository(adapter.database).listForRecord<ChemicalProduct>("ChemicalProduct",route.recordId??"")]);}catch(cause){error=cause instanceof Error?cause.message:String(cause);}finally{loading=false;}}
  function locationName(id:string){return locations.find((item)=>item.id===id)?.name??"Unknown Location";}function functionName(id:string){return functions.find((item)=>item.id===id)?.name??"Unknown Function";}function processName(id:string){return processes.find((item)=>item.id===id)?.name??"Unknown Process";}function taskName(id?:string){return id?tasks.find((item)=>item.id===id)?.name??"Unknown Task":"No specific Task";}function substanceName(id:string){return substances.find((item)=>item.id===id)?.canonicalName??"Unknown Substance";}
  function editProduct(){if(product)void goto(`/master/products/${product.id}/edit`);}function addSds(){if(product)void goto(`/master/products/${product.id}/sds/new`);}
  async function archive(reason:string){if(!application||!product)return;await application.products.archive(product.id,product.revision,reason);archiveOpen=false;await load();}async function restore(){if(!application||!product)return;await application.products.restore(product.id,product.revision);await load();}function scopeSite(id:string){setWorkspaceScope({siteId:id});}
</script>

{#if loading}<section class="product-loading" role="status">Loading Product workspace…</section>{:else if error||!product}<section class="product-loading"><ErrorState message={error??"Product not found"} onRetry={()=>void load()}/></section>{:else}
<RecordWorkspace title={product.productName} recordType="Chemical Product" summary={product.description||`${product.formulationType} · ${product.physicalState}`} contextPath={[{label:"Products",href:"/master/products"},{label:product.productName}]} statuses={[{label:"Lifecycle",value:product.lifecycleStatus==="archived"?"Archived":product.status,tone:product.status==="Active"?"positive":"neutral"},{label:"Review",value:currentSds?.reviewStatus??"SDS not reviewed",tone:currentSds?.reviewStatus==="Accepted"?"positive":"warning"},{label:"Data quality",value:completeness.every((item)=>item.complete)?"Verified":"Needs verification",tone:completeness.every((item)=>item.complete)?"positive":"warning"},{label:"Sync / exchange",value:product.lastExchangePackageId?"Exchanged":"Local changes",tone:"information"}]} actions={[{label:"Edit",onSelect:editProduct,primary:true},{label:"Add SDS Revision",onSelect:addSds}]} moreActions={product.lifecycleStatus==="archived"?[{label:"Restore",onSelect:()=>void restore()}]:[{label:"Archive…",onSelect:()=>archiveOpen=true}]} tabs={["Overview","Composition","SDS","Site Inventory","Chemical Uses","Exposure Agents","History"].map((label)=>({id:label.toLowerCase().replaceAll(" ","-"),label}))} {activeTab} onTabChange={(id)=>activeTab=id}>
  {#if activeTab==="overview"}
    <div class="product-summary"><SummaryCard label="Manufacturer" value={manufacturer?.name??(product.manufacturerUnknown?"Unknown":"Missing")} detail={product.productCode}/><SummaryCard label="Formulation" value={product.formulationType}/><SummaryCard label="Physical state" value={product.physicalState}/><SummaryCard label="Current SDS" value={currentSds?.reviewStatus??"Missing"} href="#sds" tone={currentSds?"default":"attention"}/><SummaryCard label="Sites present" value={sites.length} href="#site-inventory"/><SummaryCard label="Documented Uses" value={productUses.length} href="#chemical-uses"/><SummaryCard label="Data-quality gaps" value={completeness.filter((item)=>!item.complete).length} href="/reports/data-quality" tone={completeness.some((item)=>!item.complete)?"attention":"default"}/></div>
    <div class="overview-grid"><CompletenessPanel rules={completeness}/><ConnectedRecords records={[{label:"Composition",value:productComposition.length,href:"#composition"},{label:"SDS revisions",value:productSds.length,href:"#sds"},{label:"Site Inventory",value:productInventory.length,href:"#site-inventory"},{label:"Chemical Uses",value:productUses.length,href:"#chemical-uses"},{label:"Exposure Agents",value:0,href:"/ih/exposure-agents"}]}/></div>
  {:else if activeTab==="composition"}<RelationshipList title="Composition" items={productComposition.map((item)=>({id:item.id,name:substanceName(item.substanceId),type:item.componentRole,detail:`${item.minimumConcentration??"?"}–${item.maximumConcentration??"?"} ${item.concentrationUnit}`,href:`/master/substances/${item.substanceId}`}))} emptyMessage="No composition is documented for this Product."/>
  {:else if activeTab==="sds"}<div class="tab-heading"><h2>SDS history</h2><a href={`/master/products/${productId}/sds/new`}>Add SDS Revision</a></div><RelationshipList title="Safety Data Sheets" items={productSds.map((item)=>({id:item.id,name:`${item.revisionDate??"Date unknown"} · ${item.language}`,type:item.currentStatus,detail:`${item.jurisdiction} · ${item.reviewStatus}`,href:`/master/products/${productId}/sds/${item.id}`,status:item.reviewStatus}))} emptyMessage="No SDS revisions are documented."/>
  {:else if activeTab==="site-inventory"}<div class="inventory-tree">{#each sites.filter((site)=>productInventory.some((item)=>item.siteId===site.id)) as site}<section><h2><button type="button" onclick={()=>scopeSite(site.id)}>{site.name}</button></h2>{#each productInventory.filter((item)=>item.siteId===site.id) as item}<a href={`/master/inventory/${item.id}`}><span>{locationName(item.storageLocationId)}</span><strong>{item.observedQuantity??"Unknown"} {item.quantityUnit??""}</strong><small>{item.containerType} · {item.inventoryStatus}</small></a>{/each}</section>{:else}<EmptyState title="No Site inventory" message="This Product is not currently recorded in Site Inventory." actionLabel="Record inventory" onAction={()=>void goto("/master/inventory/new")}/>{/each}</div>
  {:else if activeTab==="chemical-uses"}<div class="use-tree">{#each sites.filter((site)=>productUses.some((item)=>item.siteId===site.id)) as site}<section><h2>{site.name}</h2>{#each [...new Set(productUses.filter((item)=>item.siteId===site.id).map((item)=>item.operationalFunctionId))] as functionId}<div class="function-group"><h3>{functionName(functionId)}</h3>{#each productUses.filter((item)=>item.siteId===site.id&&item.operationalFunctionId===functionId) as item}<a href={`/master/chemical-uses/${item.id}`}><strong>{processName(item.processId)}</strong><span>{taskName(item.taskId)} · {item.operatingCondition}</span><small>{item.applicationMethod} · {item.frequency}</small></a>{/each}</div>{/each}</section>{:else}<EmptyState title="No documented Chemical Uses" message="Inventory does not imply use. Document the work context when this Product is actively used." actionLabel="Document Chemical Use" onAction={()=>void goto("/master/chemical-uses/new")}/>{/each}</div>
  {:else if activeTab==="history"}<RevisionTimeline revisions={revisions.map((item)=>({id:item.id,revision:item.revision,operation:item.operation,changedAt:item.changedAt,changedBy:item.changedBy}))}/>
  {:else}<EmptyState title="No Exposure Agents connected" message="Exposure-agent relationships will appear here without changing Product identity."/>
  {/if}
</RecordWorkspace>
{/if}
{#if archiveOpen&&product}<ConfirmationDialog title={`Archive ${product.productName}?`} consequence="The Product will no longer be available for new active Inventory or Chemical Use records. Existing history remains connected." dependencyWarning={`${productInventory.length} inventory record(s), ${productUses.length} Chemical Use record(s), and ${productSds.length} SDS revision(s) remain in history.`} confirmLabel="Archive Product" reasonRequired destructive onConfirm={archive} onCancel={()=>archiveOpen=false}/>{/if}

<style>.product-loading{padding:28px}.product-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-bottom:15px}.overview-grid{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(300px,1.2fr);gap:14px}.tab-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.tab-heading h2{margin:0;font-size:1rem}.tab-heading a{border:1px solid var(--color-action);border-radius:var(--radius-control);color:var(--color-action);font-size:.75rem;font-weight:750;padding:7px 10px;text-decoration:none}.inventory-tree,.use-tree{display:grid;gap:12px}.inventory-tree>section,.use-tree>section{overflow:hidden;border:1px solid var(--color-border);border-radius:var(--radius-surface);background:var(--color-surface)}.inventory-tree h2,.use-tree h2{margin:0;border-bottom:1px solid var(--color-border);font-size:.9rem;padding:11px 14px}.inventory-tree h2 button{border:0;background:transparent;color:var(--color-text);font-weight:750}.inventory-tree a{display:grid;grid-template-columns:1fr auto;gap:3px;border-bottom:1px solid var(--color-border);color:var(--color-text);font-size:.78rem;padding:10px 14px;text-decoration:none}.inventory-tree a:last-child{border-bottom:0}.inventory-tree small{grid-column:1 / -1;color:var(--color-muted)}.function-group{display:grid;grid-template-columns:minmax(140px,.35fr)1fr;border-bottom:1px solid var(--color-border)}.function-group:last-child{border-bottom:0}.function-group h3{margin:0;color:var(--color-action);font-size:.8rem;padding:11px 14px}.function-group a{display:grid;gap:2px;border-left:1px solid var(--color-border);border-bottom:1px solid var(--color-border);color:var(--color-text);padding:9px 12px;text-decoration:none}.function-group a:last-child{border-bottom:0}.function-group a span,.function-group a small{color:var(--color-muted);font-size:.7rem}@media(max-width:760px){.overview-grid,.function-group{grid-template-columns:1fr}.function-group a{border-left:0}}</style>
