<script lang="ts">
  import type { Snippet } from "svelte";
  import { Check } from "lucide-svelte";
  export interface GuidedFormStep { id: string; label: string; description?: string; }
  interface Props { title: string; steps: GuidedFormStep[]; activeIndex: number; onStepSelect?: (index: number) => void; children?: Snippet; }
  let { title, steps, activeIndex, onStepSelect = () => {}, children }: Props = $props();
</script>
<div class="guided-form"><aside><span class="eyebrow">Guided workflow</span><h2>{title}</h2><ol>{#each steps as step,index}<li class:active={index===activeIndex} class:complete={index<activeIndex}><button type="button" onclick={()=>onStepSelect(index)} disabled={index>activeIndex}><span class="number">{#if index<activeIndex}<Check size={14}/>{:else}{index+1}{/if}</span><span><strong>{step.label}</strong>{#if step.description}<small>{step.description}</small>{/if}</span></button></li>{/each}</ol></aside><section class="step-content">{#if children}{@render children()}{/if}</section></div>
<style>.guided-form{display:grid;grid-template-columns:minmax(210px,280px) minmax(0,1fr);overflow:hidden;border:1px solid var(--color-border);border-radius:10px;background:var(--color-surface)}aside{border-right:1px solid var(--color-border);background:var(--color-surface-subtle);padding:20px 16px}.eyebrow{color:var(--color-action);font-size:.68rem;font-weight:750;text-transform:uppercase}h2{margin:4px 0 18px;font-size:1.05rem}ol{display:grid;gap:3px;margin:0;padding:0;list-style:none}li button{display:grid;grid-template-columns:28px 1fr;align-items:start;gap:8px;width:100%;border:0;border-radius:var(--radius-control);background:transparent;color:var(--color-muted);padding:8px;text-align:left}li button:not(:disabled):hover{background:var(--color-surface)}li.active button{background:var(--color-accent-soft);color:var(--color-action)}li.complete button{color:var(--color-positive-text)}.number{display:grid;place-items:center;width:24px;height:24px;border:1px solid currentColor;border-radius:50%;font-size:.68rem;font-weight:800}li button>span:last-child{display:grid;gap:1px}strong{color:var(--color-text);font-size:.78rem}small{font-size:.68rem}.step-content{min-width:0;padding:22px}@media(max-width:760px){.guided-form{grid-template-columns:1fr}aside{overflow-x:auto;border-right:0;border-bottom:1px solid var(--color-border);padding:13px}aside h2{margin-bottom:9px}ol{display:flex}li{min-width:145px}.step-content{padding:17px}}</style>
