import type { LifecycleMetadata } from "./lifecycle.types";

export type CampaignFieldType = "text" | "textarea" | "select" | "multiselect" | "checkbox";
export type CampaignFieldRelationName =
  | "locations"
  | "processes"
  | "equipment"
  | "chemicals"
  | "hazards"
  | "controls"
  | "riskAssessments"
  | "segs"
  | "findings"
  | "incidents"
  | "complianceItems"
  | "correctiveActions";
export type CampaignFieldRelation = CampaignFieldRelationName | string;

export interface CampaignFieldDefinition {
  name: string;
  label: string;
  type?: CampaignFieldType;
  required?: boolean;
  options?: readonly string[];
  relation?: CampaignFieldRelation;
  defaultValue?: string | boolean | string[];
  rows?: number;
  placeholder?: string;
  helperText?: string;
}

export interface CampaignRegisterDefinition {
  kind: string;
  collection: string;
  basePath: string;
  breadcrumbs: string;
  sidebarSection: string;
  sidebarTitle: string;
  title: string;
  recordLabel: string;
  pluralRecordLabel: string;
  summary: string;
  businessPrefix: string;
  typeOptions: readonly string[];
  statusOptions: readonly string[];
  defaultType: string;
  defaultStatus: string;
  fields: readonly CampaignFieldDefinition[];
  seed?: Record<string, unknown>;
}

export type CampaignRecordValue = string | string[] | boolean | null | undefined;

export interface CampaignRecord extends LifecycleMetadata {
  id: string;
  businessId: string;
  title: string;
  type: string;
  status: string;
  summary: string;
  owner: string;
  locationId: string;
  processId: string;
  personId: string;
  organizationId: string;
  taskId: string;
  segId: string;
  chemicalId: string;
  equipmentId: string;
  hazardIds: string[];
  controlIds: string[];
  relatedRecordIds: string[];
  effectiveFrom: string;
  effectiveTo: string;
  dueDate: string;
  reviewDate: string;
  evidenceReference: string;
  notes: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: CampaignRecordValue;
}

const lifecycleStatuses = [
  "Draft",
  "Active",
  "In Review",
  "Needs Review",
  "Complete",
  "Closed",
  "Superseded",
  "Cancelled",
] as const;

const workStatuses = [
  "Planned",
  "Active",
  "In Progress",
  "Blocked",
  "Ready With Conditions",
  "Complete",
  "Closed",
] as const;

const reviewStatuses = [
  "Not Started",
  "Required",
  "In Review",
  "Approved",
  "Rejected",
  "Conditional",
  "Complete",
] as const;

const trainingStatuses = ["Current", "Due Soon", "Overdue", "Not Completed", "Expired"] as const;
const severityStatuses = ["Low", "Medium", "High", "Critical"] as const;
const determinationStatuses = [
  "Not Yet Determined",
  "Acceptable",
  "Uncertain",
  "Monitoring Required",
  "Controlled With Conditions",
  "Unacceptable",
] as const;

const baseFields = {
  businessId: {
    name: "businessId",
    label: "Business ID",
    helperText: "Leave blank to generate a stable migration-facing identifier.",
  },
  title: { name: "title", label: "Title", required: true },
  type: { name: "type", label: "Type", type: "select" as const, required: true },
  status: { name: "status", label: "Status", type: "select" as const, required: true },
  summary: { name: "summary", label: "Summary", type: "textarea" as const, rows: 3 },
  owner: { name: "owner", label: "Owner / Responsible Party" },
  locationId: { name: "locationId", label: "Location", type: "select" as const, relation: "locations" as const },
  processId: { name: "processId", label: "Process", type: "select" as const, relation: "processes" as const },
  personId: { name: "personId", label: "Person", type: "select" as const, relation: "people" as const },
  organizationId: {
    name: "organizationId",
    label: "Organization",
    type: "select" as const,
    relation: "organizations" as const,
  },
  taskId: { name: "taskId", label: "Task / Work Activity", type: "select" as const, relation: "tasks" as const },
  segId: { name: "segId", label: "SEG", type: "select" as const, relation: "segs" as const },
  chemicalId: { name: "chemicalId", label: "Chemical", type: "select" as const, relation: "chemicals" as const },
  equipmentId: { name: "equipmentId", label: "Equipment", type: "select" as const, relation: "equipment" as const },
  hazardIds: { name: "hazardIds", label: "Hazards", type: "multiselect" as const, relation: "hazards" as const },
  controlIds: { name: "controlIds", label: "Controls", type: "multiselect" as const, relation: "controls" as const },
  relatedRecordIds: { name: "relatedRecordIds", label: "Related Records", type: "multiselect" as const },
  effectiveFrom: { name: "effectiveFrom", label: "Effective From", placeholder: "YYYY-MM-DD" },
  effectiveTo: { name: "effectiveTo", label: "Effective To", placeholder: "YYYY-MM-DD" },
  dueDate: { name: "dueDate", label: "Due Date", placeholder: "YYYY-MM-DD" },
  reviewDate: { name: "reviewDate", label: "Review Date", placeholder: "YYYY-MM-DD" },
  evidenceReference: { name: "evidenceReference", label: "Evidence / Reference" },
  notes: { name: "notes", label: "Notes", type: "textarea" as const, rows: 3 },
} satisfies Record<string, CampaignFieldDefinition>;

function register<const TDefinition extends Omit<CampaignRegisterDefinition, "fields"> & {
  fields?: readonly CampaignFieldDefinition[];
}>(
  definition: TDefinition,
): Omit<TDefinition, "fields"> & CampaignRegisterDefinition {
  return {
    ...definition,
    fields: [
      baseFields.businessId,
      baseFields.title,
      { ...baseFields.type, options: definition.typeOptions },
      { ...baseFields.status, options: definition.statusOptions },
      ...(definition.fields ?? []),
      baseFields.summary,
      baseFields.evidenceReference,
      baseFields.notes,
    ],
  } as Omit<TDefinition, "fields"> & CampaignRegisterDefinition;
}

export const CAMPAIGN_REGISTER_DEFINITIONS = [
  register({
    kind: "organizations",
    collection: "organizations",
    basePath: "/people/organizations",
    breadcrumbs: "People and Work",
    sidebarSection: "people-work",
    sidebarTitle: "People & Work",
    title: "Organizations",
    recordLabel: "organization",
    pluralRecordLabel: "organizations",
    summary: "Model internal groups, contractors, laboratories, vendors, agencies, and other reusable HSE organizations.",
    businessPrefix: "ORG",
    typeOptions: ["ADAMA Entity", "Contractor", "Temporary Agency", "Laboratory", "Waste Vendor", "Service Vendor", "Regulator", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Contractor",
    defaultStatus: "Active",
    fields: [
      baseFields.owner,
      { name: "primaryContact", label: "Primary Contact" },
      { name: "sitesServedIds", label: "Sites Served", type: "multiselect", relation: "locations" },
    ],
    seed: {
      id: "org-demo-industrial-services",
      businessId: "ORG-0001",
      title: "Industrial Services Contractor",
      type: "Contractor",
      status: "Active",
      primaryContact: "Contractor Safety Lead",
      summary: "Seed contractor organization for readiness, training, incident, and work-scope review.",
    },
  }),
  register({
    kind: "people",
    collection: "people",
    basePath: "/people/workers",
    breadcrumbs: "People and Work",
    sidebarSection: "people-work",
    sidebarTitle: "People & Work",
    title: "People",
    recordLabel: "person",
    pluralRecordLabel: "people",
    summary: "Represent employees, contractors, inspectors, investigators, owners, and other HSE-relevant contacts.",
    businessPrefix: "PER",
    typeOptions: ["Employee", "Contractor", "Temporary Worker", "Inspector", "Investigator", "Owner", "External Contact"],
    statusOptions: lifecycleStatuses,
    defaultType: "Employee",
    defaultStatus: "Active",
    fields: [
      { name: "employeeIdentifier", label: "Employee / Worker ID" },
      baseFields.organizationId,
      { name: "jobTitle", label: "Job Title" },
      { name: "department", label: "Department" },
      { name: "supervisorPersonId", label: "Supervisor", type: "select", relation: "people" },
      { name: "primarySiteId", label: "Primary Site", type: "select", relation: "locations" },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
    ],
    seed: {
      id: "person-demo-hse-lead",
      businessId: "PER-0001",
      title: "Demo HSE Lead",
      type: "Employee",
      status: "Active",
      jobTitle: "HSE Lead",
      primarySiteId: "loc-demo-main-facility",
      summary: "Seed responsible person for ownership, SEG membership, training, and review relationships.",
    },
  }),
  register({
    kind: "seg-memberships",
    collection: "segMemberships",
    basePath: "/people/seg-memberships",
    breadcrumbs: "People and Work",
    sidebarSection: "people-work",
    sidebarTitle: "People & Work",
    title: "SEG Memberships",
    recordLabel: "SEG membership",
    pluralRecordLabel: "SEG memberships",
    summary: "Preserve effective-dated relationships between people and SEGs for current and historical exposure context.",
    businessPrefix: "SEGM",
    typeOptions: ["Current Membership", "Historical Membership", "Temporary Assignment"],
    statusOptions: lifecycleStatuses,
    defaultType: "Current Membership",
    defaultStatus: "Active",
    fields: [
      { ...baseFields.personId, required: true },
      { ...baseFields.segId, required: true },
      { ...baseFields.effectiveFrom, required: true },
      baseFields.effectiveTo,
      { name: "basis", label: "Basis / Rationale", type: "textarea", rows: 3 },
    ],
    seed: {
      id: "segm-demo-hse-lead-chemical-handlers",
      businessId: "SEGM-0001",
      title: "Demo HSE Lead - Chemical Handlers",
      type: "Current Membership",
      status: "Active",
      personId: "person-demo-hse-lead",
      segId: "seg-demo-chemical-handlers",
      effectiveFrom: "2026-07-01",
      basis: "Seed effective-dated membership for exposure-context verification.",
    },
  }),
  register({
    kind: "tasks",
    collection: "tasks",
    basePath: "/operations/tasks",
    breadcrumbs: "Operations",
    sidebarSection: "operations",
    sidebarTitle: "Operations",
    title: "Tasks",
    recordLabel: "task",
    pluralRecordLabel: "tasks",
    summary: "Represent distinct work activities under processes so HSE records can point to the work where risk occurs.",
    businessPrefix: "TASK",
    typeOptions: ["Routine Operation", "Maintenance", "Cleaning", "Startup", "Shutdown", "Contractor Work", "Emergency Response"],
    statusOptions: lifecycleStatuses,
    defaultType: "Routine Operation",
    defaultStatus: "Active",
    fields: [
      { ...baseFields.processId, required: true },
      baseFields.locationId,
      { name: "segIds", label: "Related SEGs", type: "multiselect", relation: "segs" },
      { name: "personIds", label: "Assigned People", type: "multiselect", relation: "people" },
      { name: "chemicalIds", label: "Related Chemicals", type: "multiselect", relation: "chemicals" },
      { name: "equipmentIds", label: "Related Equipment", type: "multiselect", relation: "equipment" },
      baseFields.hazardIds,
      baseFields.controlIds,
    ],
    seed: {
      id: "task-demo-baler-loading",
      businessId: "TASK-0001",
      title: "Baler Loading",
      type: "Routine Operation",
      status: "Active",
      processId: "process-demo-equipment-maint",
      locationId: "loc-demo-workshop",
      equipmentIds: ["equipment-demo-dust-collector"],
      hazardIds: ["hazard-demo-noise"],
      controlIds: ["control-demo-hearing-protection"],
      summary: "Seed task used by PSSR, training, exposure, and incident contexts.",
    },
  }),
  register({
    kind: "contractor-scopes",
    collection: "contractorScopes",
    basePath: "/people/contractor-scopes",
    breadcrumbs: "People and Work",
    sidebarSection: "people-work",
    sidebarTitle: "People & Work",
    title: "Contractor Scopes",
    recordLabel: "contractor scope",
    pluralRecordLabel: "contractor scopes",
    summary: "Connect contractor organizations, workers, sites, tasks, readiness, incidents, findings, and actions.",
    businessPrefix: "CON",
    typeOptions: ["Site Service", "Maintenance", "Construction", "Waste Service", "Laboratory Service", "Special Project"],
    statusOptions: workStatuses,
    defaultType: "Site Service",
    defaultStatus: "Planned",
    fields: [
      { ...baseFields.organizationId, required: true },
      { name: "personIds", label: "Contractor Workers", type: "multiselect", relation: "people" },
      baseFields.locationId,
      { name: "taskIds", label: "Work Activities", type: "multiselect", relation: "tasks" },
      { name: "readinessSummary", label: "Readiness Summary", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "inspections",
    collection: "inspections",
    basePath: "/field/inspections",
    breadcrumbs: "Field Work",
    sidebarSection: "field-work",
    sidebarTitle: "Field Work",
    title: "Inspections",
    recordLabel: "inspection",
    pluralRecordLabel: "inspections",
    summary: "Preserve field activity purpose, scope, criteria, participants, findings, evidence, and follow-up.",
    businessPrefix: "INSP",
    typeOptions: ["General Safety", "HSE Walkthrough", "Equipment", "Environmental", "Program", "Audit", "Assessment"],
    statusOptions: workStatuses,
    defaultType: "General Safety",
    defaultStatus: "Planned",
    fields: [
      { ...baseFields.locationId, required: true },
      baseFields.processId,
      baseFields.taskId,
      { name: "inspectionDate", label: "Inspection Date", required: true, placeholder: "YYYY-MM-DD" },
      { name: "inspectorPersonId", label: "Inspector", type: "select", relation: "people" },
      { name: "participantPersonIds", label: "Participants", type: "multiselect", relation: "people" },
      { name: "scope", label: "Scope", type: "textarea", rows: 3 },
      { name: "criteriaReference", label: "Checklist / Criteria Reference" },
      { name: "findingIds", label: "Linked Findings", type: "multiselect", relation: "findings" },
      { name: "actionIds", label: "Linked Actions", type: "multiselect", relation: "correctiveActions" },
    ],
    seed: {
      id: "insp-demo-egress-walkthrough",
      businessId: "INSP-0001",
      title: "Emergency Egress Walkthrough",
      type: "HSE Walkthrough",
      status: "In Progress",
      locationId: "loc-demo-main-facility",
      inspectionDate: "2026-07-08",
      inspectorPersonId: "person-demo-hse-lead",
      findingIds: ["finding-demo-egress"],
      actionIds: ["ca-demo-clear-egress"],
      summary: "Seed inspection demonstrating the inspection to finding to action chain.",
    },
  }),
  register({
    kind: "exposure-agents",
    collection: "exposureAgents",
    basePath: "/ih/exposure-agents",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Exposure Agents",
    recordLabel: "exposure agent",
    pluralRecordLabel: "exposure agents",
    summary: "Represent chemical and nonchemical occupational agents without forcing every exposure into the Chemical register.",
    businessPrefix: "AGT",
    typeOptions: ["Chemical", "Noise", "Heat", "Vibration", "Biological", "Radiation", "Ergonomic", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Chemical",
    defaultStatus: "Active",
    fields: [
      baseFields.chemicalId,
      { name: "substanceRelationship", label: "Chemical / Substance Relationship" },
      { name: "referenceInformation", label: "Reference Information", type: "textarea", rows: 3 },
    ],
    seed: {
      id: "agent-demo-acetone-vapor",
      businessId: "AGT-0001",
      title: "Acetone Vapor",
      type: "Chemical",
      status: "Active",
      chemicalId: "chem-demo-acetone",
      summary: "Seed occupational exposure agent linked to the chemical inventory.",
    },
  }),
  register({
    kind: "exposure-limits",
    collection: "exposureLimits",
    basePath: "/ih/exposure-limits",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Exposure Limits",
    recordLabel: "exposure limit",
    pluralRecordLabel: "exposure limits",
    summary: "Store multiple limits or criteria per exposure agent with source, unit, averaging period, and effective status.",
    businessPrefix: "OEL",
    typeOptions: ["OSHA PEL", "ACGIH TLV-TWA", "ACGIH STEL", "NIOSH REL", "Company OEL", "Ceiling", "Other"],
    statusOptions: ["Active", "Superseded", "Under Review", "Retired"],
    defaultType: "ACGIH TLV-TWA",
    defaultStatus: "Active",
    fields: [
      { name: "exposureAgentId", label: "Exposure Agent", type: "select", relation: "exposureAgents", required: true },
      { name: "limitValue", label: "Limit Value", required: true },
      { name: "unit", label: "Unit", required: true, placeholder: "ppm, mg/m3, dBA" },
      { name: "averagingPeriod", label: "Averaging Period" },
      { name: "notation", label: "Notation" },
      baseFields.effectiveFrom,
      baseFields.effectiveTo,
    ],
    seed: {
      id: "limit-demo-acetone-tlv",
      businessId: "OEL-0001",
      title: "Acetone ACGIH TLV-TWA",
      type: "ACGIH TLV-TWA",
      status: "Active",
      exposureAgentId: "agent-demo-acetone-vapor",
      limitValue: "250",
      unit: "ppm",
      averagingPeriod: "8-hour TWA",
      effectiveFrom: "2026-01-01",
    },
  }),
  register({
    kind: "exposure-assessments",
    collection: "exposureAssessments",
    basePath: "/ih/exposure-assessments",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Exposure Assessments",
    recordLabel: "exposure assessment",
    pluralRecordLabel: "exposure assessments",
    summary: "Capture qualitative exposure reasoning, monitoring need, controls, confidence, and review dates.",
    businessPrefix: "EA",
    typeOptions: ["Qualitative Assessment", "Review Update", "Baseline Assessment", "Targeted Assessment"],
    statusOptions: ["Draft", "Monitoring Required", "Controlled With Conditions", "Acceptable", "Unacceptable", "Needs Review"],
    defaultType: "Qualitative Assessment",
    defaultStatus: "Draft",
    fields: [
      baseFields.segId,
      baseFields.personId,
      baseFields.taskId,
      baseFields.processId,
      baseFields.locationId,
      { name: "exposureAgentId", label: "Exposure Agent", type: "select", relation: "exposureAgents", required: true },
      { name: "routes", label: "Exposure Routes" },
      { name: "frequency", label: "Frequency" },
      { name: "duration", label: "Duration" },
      baseFields.controlIds,
      { name: "historicalDataReviewed", label: "Historical Data Reviewed", type: "textarea", rows: 3 },
      { name: "qualitativeRating", label: "Qualitative Rating", type: "select", options: severityStatuses },
      { name: "monitoringNeed", label: "Monitoring Need Decision" },
      { name: "assessorPersonId", label: "Assessor", type: "select", relation: "people" },
      baseFields.reviewDate,
      { name: "confidence", label: "Confidence", type: "select", options: ["Low", "Medium", "High"] },
    ],
  }),
  register({
    kind: "exposure-determinations",
    collection: "exposureDeterminations",
    basePath: "/ih/exposure-determinations",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Exposure Determinations",
    recordLabel: "exposure determination",
    pluralRecordLabel: "exposure determinations",
    summary: "Preserve professional exposure conclusions distinct from raw monitoring results.",
    businessPrefix: "DET",
    typeOptions: ["Initial Determination", "Updated Determination", "Campaign Interpretation"],
    statusOptions: determinationStatuses,
    defaultType: "Initial Determination",
    defaultStatus: "Not Yet Determined",
    fields: [
      { name: "exposureAssessmentId", label: "Exposure Assessment", type: "select", relation: "exposureAssessments", required: true },
      { name: "basis", label: "Basis", type: "textarea", rows: 3, required: true },
      { name: "exposureLimitIds", label: "Applicable Limits", type: "multiselect", relation: "exposureLimits" },
      { name: "requiredControlIds", label: "Required Controls", type: "multiselect", relation: "controls" },
      { name: "requiredActionIds", label: "Required Actions", type: "multiselect", relation: "correctiveActions" },
      baseFields.reviewDate,
    ],
  }),
  register({
    kind: "sampling-campaigns",
    collection: "samplingCampaigns",
    basePath: "/ih/sampling-campaigns",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Sampling Campaigns",
    recordLabel: "sampling campaign",
    pluralRecordLabel: "sampling campaigns",
    summary: "Group monitoring records under objective, strategy, agent, SEG, task, methods, lab, and interpretation.",
    businessPrefix: "SC",
    typeOptions: ["Baseline Monitoring", "Follow-up Monitoring", "Personal Sampling", "Area Sampling", "Noise Survey"],
    statusOptions: workStatuses,
    defaultType: "Personal Sampling",
    defaultStatus: "Planned",
    fields: [
      { name: "exposureAssessmentId", label: "Exposure Assessment", type: "select", relation: "exposureAssessments" },
      { name: "exposureAgentIds", label: "Exposure Agents", type: "multiselect", relation: "exposureAgents" },
      { name: "segIds", label: "SEGs", type: "multiselect", relation: "segs" },
      { name: "personIds", label: "People", type: "multiselect", relation: "people" },
      { name: "taskIds", label: "Tasks", type: "multiselect", relation: "tasks" },
      { name: "method", label: "Method" },
      { name: "laboratoryOrganizationId", label: "Laboratory", type: "select", relation: "organizations" },
      { name: "plannedDate", label: "Planned Date", placeholder: "YYYY-MM-DD" },
      { name: "actualDate", label: "Actual Date", placeholder: "YYYY-MM-DD" },
      { name: "interpretationSummary", label: "Interpretation Summary", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "control-verifications",
    collection: "controlVerifications",
    basePath: "/ih/control-verifications",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Control Verifications",
    recordLabel: "control verification",
    pluralRecordLabel: "control verifications",
    summary: "Record whether a control is performing as expected and preserve deficiencies and follow-up.",
    businessPrefix: "CV",
    typeOptions: ["LEV Test", "Inspection", "Interlock Test", "Performance Check", "Program Verification"],
    statusOptions: ["Effective", "Needs Review", "Deficient", "Ineffective", "Closed"],
    defaultType: "Inspection",
    defaultStatus: "Needs Review",
    fields: [
      { ...baseFields.controlIds, required: true },
      { name: "verificationDate", label: "Verification Date", required: true, placeholder: "YYYY-MM-DD" },
      { name: "verificationMethod", label: "Verification Method", required: true },
      { name: "expectedCondition", label: "Expected Condition", type: "textarea", rows: 3 },
      { name: "actualCondition", label: "Actual Condition", type: "textarea", rows: 3 },
      { name: "verifierPersonId", label: "Verifier", type: "select", relation: "people" },
      { name: "deficiency", label: "Deficiency", type: "textarea", rows: 3 },
      { name: "actionIds", label: "Linked Actions", type: "multiselect", relation: "correctiveActions" },
    ],
  }),
  register({
    kind: "hse-programs",
    collection: "hsePrograms",
    basePath: "/ih/programs",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "HSE Programs",
    recordLabel: "HSE program",
    pluralRecordLabel: "HSE programs",
    summary: "Register HSE programs such as respiratory protection, hearing conservation, HAZCOM, LOTO, and medical surveillance.",
    businessPrefix: "PROG",
    typeOptions: ["Respiratory Protection", "Hearing Conservation", "Hazard Communication", "Medical Surveillance", "Confined Space", "LOTO", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Hazard Communication",
    defaultStatus: "Active",
    fields: [baseFields.owner, baseFields.reviewDate],
  }),
  register({
    kind: "program-applicabilities",
    collection: "programApplicabilities",
    basePath: "/ih/program-applicability",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Program Applicability",
    recordLabel: "program applicability",
    pluralRecordLabel: "program applicability records",
    summary: "Explain why a person, SEG, task, agent, or condition falls within an HSE program.",
    businessPrefix: "APP",
    typeOptions: ["Person", "SEG", "Task", "Exposure Agent", "Condition"],
    statusOptions: lifecycleStatuses,
    defaultType: "Person",
    defaultStatus: "Active",
    fields: [
      { name: "hseProgramId", label: "HSE Program", type: "select", relation: "hsePrograms", required: true },
      baseFields.personId,
      baseFields.segId,
      baseFields.taskId,
      { name: "exposureAgentId", label: "Exposure Agent", type: "select", relation: "exposureAgents" },
      { name: "basis", label: "Applicability Basis", type: "textarea", rows: 3, required: true },
      baseFields.effectiveFrom,
      baseFields.effectiveTo,
    ],
  }),
  register({
    kind: "medical-surveillance",
    collection: "medicalSurveillance",
    basePath: "/ih/medical-surveillance",
    breadcrumbs: "Industrial Hygiene",
    sidebarSection: "industrial-hygiene",
    sidebarTitle: "Industrial Hygiene",
    title: "Medical Surveillance",
    recordLabel: "medical surveillance record",
    pluralRecordLabel: "medical surveillance records",
    summary: "Track administrative surveillance requirement, due, completion, provider, clearance, and restrictions without storing clinical records.",
    businessPrefix: "MS",
    typeOptions: ["Respirator Clearance", "Hearing Conservation", "Medical Surveillance", "Fitness Review", "Other"],
    statusOptions: trainingStatuses,
    defaultType: "Medical Surveillance",
    defaultStatus: "Not Completed",
    fields: [
      { ...baseFields.personId, required: true },
      { name: "hseProgramId", label: "Program", type: "select", relation: "hsePrograms" },
      { name: "requirementBasis", label: "Requirement Basis", type: "textarea", rows: 3 },
      { name: "providerOrganizationId", label: "Provider", type: "select", relation: "organizations" },
      baseFields.dueDate,
      { name: "completedDate", label: "Completed Date", placeholder: "YYYY-MM-DD" },
      { name: "clearanceStatus", label: "Clearance Status" },
      { name: "restrictionsSummary", label: "Restrictions Summary", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "training-courses",
    collection: "trainingCourses",
    basePath: "/training/courses",
    breadcrumbs: "Training",
    sidebarSection: "training",
    sidebarTitle: "Training",
    title: "Training Courses",
    recordLabel: "training course",
    pluralRecordLabel: "training courses",
    summary: "Define reusable HSE courses and evidence expectations.",
    businessPrefix: "COURSE",
    typeOptions: ["General HSE", "Task Specific", "Chemical", "Equipment", "Program", "Contractor", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "General HSE",
    defaultStatus: "Active",
    fields: [
      { name: "provider", label: "Provider / Owner" },
      { name: "evidenceExpectation", label: "Evidence Expectation", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "training-requirements",
    collection: "trainingRequirements",
    basePath: "/training/requirements",
    breadcrumbs: "Training",
    sidebarSection: "training",
    sidebarTitle: "Training",
    title: "Training Requirements",
    recordLabel: "training requirement",
    pluralRecordLabel: "training requirements",
    summary: "Explain why a course is required by person, role, SEG, task, equipment, chemical, program, or contractor scope.",
    businessPrefix: "TR",
    typeOptions: ["Person", "Role", "SEG", "Task", "Equipment", "Chemical", "Program", "Contractor"],
    statusOptions: lifecycleStatuses,
    defaultType: "Task",
    defaultStatus: "Active",
    fields: [
      { name: "trainingCourseId", label: "Course", type: "select", relation: "trainingCourses", required: true },
      { name: "requirementSource", label: "Requirement Source", required: true },
      { name: "trigger", label: "Trigger / Applicability Basis", required: true },
      baseFields.personId,
      baseFields.segId,
      baseFields.taskId,
      baseFields.equipmentId,
      baseFields.chemicalId,
      { name: "hseProgramId", label: "HSE Program", type: "select", relation: "hsePrograms" },
      { name: "initialRequirement", label: "Initial Requirement" },
      { name: "refresherInterval", label: "Refresher Interval" },
      baseFields.effectiveFrom,
      baseFields.effectiveTo,
    ],
  }),
  register({
    kind: "training-records",
    collection: "trainingRecords",
    basePath: "/training/records",
    breadcrumbs: "Training",
    sidebarSection: "training",
    sidebarTitle: "Training",
    title: "Training Records",
    recordLabel: "training record",
    pluralRecordLabel: "training records",
    summary: "Preserve worker completion history, expiration, evidence, status, and external source provenance.",
    businessPrefix: "TC",
    typeOptions: ["Initial", "Refresher", "Equivalent", "Imported", "Contractor Acknowledgement"],
    statusOptions: trainingStatuses,
    defaultType: "Initial",
    defaultStatus: "Current",
    fields: [
      { ...baseFields.personId, required: true },
      { name: "trainingCourseId", label: "Course", type: "select", relation: "trainingCourses", required: true },
      { name: "completionDate", label: "Completion Date", required: true, placeholder: "YYYY-MM-DD" },
      { name: "expirationDate", label: "Expiration / Next Due", placeholder: "YYYY-MM-DD" },
      { name: "instructor", label: "Instructor / Provider" },
      { name: "sourceOfRecord", label: "Source of Record" },
    ],
  }),
  register({
    kind: "management-changes",
    collection: "managementChanges",
    basePath: "/change/moc",
    breadcrumbs: "Change Control",
    sidebarSection: "change-control",
    sidebarTitle: "Change Control",
    title: "Management of Change",
    recordLabel: "MOC",
    pluralRecordLabel: "MOCs",
    summary: "Preserve proposed change, reason, affected systems, required reviews, actions, approvals, and implementation state.",
    businessPrefix: "MOC",
    typeOptions: ["Equipment", "Process", "Chemical", "Procedure", "Control", "Temporary", "Organization / Work Method", "Other"],
    statusOptions: ["Draft", "Impact Review", "Approved", "Implementation", "PSSR Required", "Closed", "Cancelled"],
    defaultType: "Equipment",
    defaultStatus: "Draft",
    fields: [
      { name: "reason", label: "Reason", type: "textarea", rows: 3, required: true },
      { name: "requestorPersonId", label: "Requestor", type: "select", relation: "people" },
      { name: "ownerPersonId", label: "Owner", type: "select", relation: "people" },
      baseFields.locationId,
      baseFields.processId,
      baseFields.taskId,
      baseFields.equipmentId,
      { name: "chemicalIds", label: "Affected Chemicals", type: "multiselect", relation: "chemicals" },
      baseFields.hazardIds,
      baseFields.controlIds,
      { name: "documentReferenceIds", label: "Documents Affected", type: "multiselect", relation: "documentReferences" },
      { name: "trainingImpact", label: "Training Impact", type: "textarea", rows: 3 },
      { name: "ihReviewStatus", label: "IH Review Status", type: "select", options: reviewStatuses },
      { name: "environmentalReviewStatus", label: "Environmental Review Status", type: "select", options: reviewStatuses },
      { name: "plannedImplementationDate", label: "Planned Implementation", placeholder: "YYYY-MM-DD" },
      { name: "actualImplementationDate", label: "Actual Implementation", placeholder: "YYYY-MM-DD" },
    ],
  }),
  register({
    kind: "change-reviews",
    collection: "changeReviews",
    basePath: "/change/reviews",
    breadcrumbs: "Change Control",
    sidebarSection: "change-control",
    sidebarTitle: "Change Control",
    title: "Change Impact Reviews",
    recordLabel: "change review",
    pluralRecordLabel: "change reviews",
    summary: "Track required MOC domain reviews, reviewers, results, and generated follow-up.",
    businessPrefix: "CR",
    typeOptions: ["Safety", "IH", "Environmental", "Procedures", "Training", "Emergency Response", "Equipment", "Chemical", "Compliance", "PSSR"],
    statusOptions: reviewStatuses,
    defaultType: "Safety",
    defaultStatus: "Required",
    fields: [
      { name: "managementChangeId", label: "MOC", type: "select", relation: "managementChanges", required: true },
      { name: "reviewerPersonId", label: "Reviewer", type: "select", relation: "people" },
      { name: "reviewResult", label: "Review Result", type: "textarea", rows: 3 },
      { name: "findingIds", label: "Findings", type: "multiselect", relation: "findings" },
      { name: "actionIds", label: "Actions", type: "multiselect", relation: "correctiveActions" },
    ],
  }),
  register({
    kind: "pssrs",
    collection: "pssrs",
    basePath: "/change/pssr",
    breadcrumbs: "Change Control",
    sidebarSection: "change-control",
    sidebarTitle: "Change Control",
    title: "PSSRs",
    recordLabel: "PSSR",
    pluralRecordLabel: "PSSRs",
    summary: "Preserve pre-startup review criteria, team, findings, blockers, actions, dispositions, and authorization.",
    businessPrefix: "PSSR",
    typeOptions: ["MOC PSSR", "Standalone PSSR", "Equipment Startup", "Process Startup"],
    statusOptions: ["Not Ready for Startup", "Ready With Approved Conditions", "Ready for Startup", "Startup Authorized", "Closed"],
    defaultType: "MOC PSSR",
    defaultStatus: "Not Ready for Startup",
    fields: [
      { name: "managementChangeId", label: "Related MOC", type: "select", relation: "managementChanges" },
      baseFields.equipmentId,
      baseFields.processId,
      baseFields.taskId,
      baseFields.locationId,
      { name: "reviewDate", label: "Review Date", placeholder: "YYYY-MM-DD" },
      { name: "reviewTeamPersonIds", label: "Review Team", type: "multiselect", relation: "people" },
      { name: "checklistReference", label: "Checklist / Criteria Reference" },
      { name: "findingIds", label: "Findings", type: "multiselect", relation: "findings" },
      { name: "actionIds", label: "Corrective Actions", type: "multiselect", relation: "correctiveActions" },
      { name: "startupBlockers", label: "Startup Blockers", type: "textarea", rows: 3 },
      { name: "blockerDisposition", label: "Blocker Disposition / Conditional Basis", type: "textarea", rows: 3 },
      { name: "authorizerPersonId", label: "Authorizer", type: "select", relation: "people" },
      { name: "authorizationDate", label: "Authorization Date", placeholder: "YYYY-MM-DD" },
      { name: "startupDate", label: "Startup Date", placeholder: "YYYY-MM-DD" },
    ],
  }),
  register({
    kind: "regulatory-requirements",
    collection: "regulatoryRequirements",
    basePath: "/environment/requirements",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Requirements",
    recordLabel: "requirement",
    pluralRecordLabel: "requirements",
    summary: "Track enduring regulatory, permit, corporate, procedure, and agreement requirements separately from due activities.",
    businessPrefix: "REQ",
    typeOptions: ["Regulation", "Permit", "Corporate Standard", "Internal Procedure", "Consent Order", "Agreement", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Regulation",
    defaultStatus: "Active",
    fields: [
      { name: "source", label: "Source", required: true },
      { name: "citation", label: "Citation / Reference" },
      { name: "jurisdiction", label: "Jurisdiction" },
      { name: "programArea", label: "Program / Subject Area" },
      { name: "applicabilityBasis", label: "Applicability Basis", type: "textarea", rows: 3, required: true },
      baseFields.locationId,
      { name: "ownerPersonId", label: "Responsible Owner", type: "select", relation: "people" },
      { name: "expectedEvidence", label: "Expected Evidence", type: "textarea", rows: 3 },
      baseFields.effectiveFrom,
      baseFields.effectiveTo,
    ],
  }),
  register({
    kind: "permits",
    collection: "permits",
    basePath: "/environment/permits",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Permits",
    recordLabel: "permit",
    pluralRecordLabel: "permits",
    summary: "Register permits and authorizations with authority, program, scope, dates, owners, requirements, and evidence.",
    businessPrefix: "PERMIT",
    typeOptions: ["Air", "Wastewater", "Stormwater", "Waste", "SPCC", "Operating Authorization", "Other"],
    statusOptions: ["Draft", "Active", "Renewal Due", "Expired", "Superseded", "Cancelled"],
    defaultType: "Air",
    defaultStatus: "Active",
    fields: [
      { name: "permitNumber", label: "Permit / Authorization Number", required: true },
      { name: "authorityOrganizationId", label: "Authority", type: "select", relation: "organizations" },
      { name: "program", label: "Program" },
      baseFields.locationId,
      { name: "effectiveDate", label: "Effective Date", placeholder: "YYYY-MM-DD" },
      { name: "expirationDate", label: "Expiration Date", placeholder: "YYYY-MM-DD" },
      { name: "renewalDate", label: "Renewal / Review Date", placeholder: "YYYY-MM-DD" },
      { name: "ownerPersonId", label: "Responsible Owner", type: "select", relation: "people" },
      { name: "requirementIds", label: "Linked Requirements", type: "multiselect", relation: "regulatoryRequirements" },
      { name: "reportingObligations", label: "Reporting / Monitoring Obligations", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "waste-streams",
    collection: "wasteStreams",
    basePath: "/environment/waste-streams",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Waste Streams",
    recordLabel: "waste stream",
    pluralRecordLabel: "waste streams",
    summary: "Model reusable waste streams with generation context, characterization, storage, vendor, and profile references.",
    businessPrefix: "WS",
    typeOptions: ["Hazardous", "Nonhazardous", "Universal Waste", "Recyclable", "Wastewater", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Nonhazardous",
    defaultStatus: "Active",
    fields: [
      baseFields.processId,
      baseFields.taskId,
      baseFields.locationId,
      { name: "characterization", label: "Characterization", type: "textarea", rows: 3 },
      { name: "wasteCodes", label: "Waste Codes" },
      { name: "containerRequirements", label: "Container / Accumulation Requirements", type: "textarea", rows: 3 },
      { name: "accumulationLocationId", label: "Accumulation Location", type: "select", relation: "locations" },
      { name: "vendorOrganizationId", label: "Disposal Vendor", type: "select", relation: "organizations" },
      { name: "profileReference", label: "Profile / Reference Number" },
    ],
  }),
  register({
    kind: "waste-shipments",
    collection: "wasteShipments",
    basePath: "/environment/waste-shipments",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Waste Shipments",
    recordLabel: "waste shipment",
    pluralRecordLabel: "waste shipments",
    summary: "Track shipment date, stream, quantity, transporter, destination, manifest, evidence, and status.",
    businessPrefix: "SHIP",
    typeOptions: ["Hazardous Waste", "Nonhazardous Waste", "Universal Waste", "Recycle", "Other"],
    statusOptions: ["Planned", "Shipped", "Received", "Manifest Returned", "Needs Review", "Closed"],
    defaultType: "Hazardous Waste",
    defaultStatus: "Planned",
    fields: [
      { name: "wasteStreamId", label: "Waste Stream", type: "select", relation: "wasteStreams", required: true },
      { name: "shipmentDate", label: "Shipment Date", required: true, placeholder: "YYYY-MM-DD" },
      { name: "quantity", label: "Quantity", required: true },
      { name: "unit", label: "Unit", required: true },
      { name: "transporterOrganizationId", label: "Transporter", type: "select", relation: "organizations" },
      { name: "destinationOrganizationId", label: "Destination Facility", type: "select", relation: "organizations" },
      { name: "manifestReference", label: "Manifest / Shipment Reference" },
    ],
  }),
  register({
    kind: "environmental-sources",
    collection: "environmentalSources",
    basePath: "/environment/sources",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Environmental Sources",
    recordLabel: "environmental source",
    pluralRecordLabel: "environmental sources",
    summary: "Register air emission sources, tanks, storage areas, outfalls, containment areas, and spill-potential sources.",
    businessPrefix: "ES",
    typeOptions: ["Air Emission Source", "Tank", "Storage Area", "Waste Generation Point", "Accumulation Area", "Wastewater Discharge", "Stormwater Outfall", "Secondary Containment", "Spill Potential Source", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "Storage Area",
    defaultStatus: "Active",
    fields: [
      baseFields.locationId,
      baseFields.processId,
      baseFields.equipmentId,
      { name: "chemicalIds", label: "Related Chemicals", type: "multiselect", relation: "chemicals" },
      { name: "permitIds", label: "Related Permits", type: "multiselect", relation: "permits" },
      { name: "requirementIds", label: "Related Requirements", type: "multiselect", relation: "regulatoryRequirements" },
      { name: "inspectionExpectation", label: "Inspection / Monitoring Expectations", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "environmental-inspections",
    collection: "environmentalInspections",
    basePath: "/environment/inspections",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Environmental Inspections",
    recordLabel: "environmental inspection",
    pluralRecordLabel: "environmental inspections",
    summary: "Specialize field-assurance inspections for SPCC, stormwater, waste areas, tanks, containment, and permit-driven checks.",
    businessPrefix: "EI",
    typeOptions: ["SPCC", "Stormwater", "Waste Area", "Tank", "Secondary Containment", "Permit", "Program", "Other"],
    statusOptions: workStatuses,
    defaultType: "Waste Area",
    defaultStatus: "Planned",
    fields: [
      { name: "environmentalSourceId", label: "Environmental Source", type: "select", relation: "environmentalSources" },
      { name: "requirementId", label: "Requirement", type: "select", relation: "regulatoryRequirements" },
      { name: "permitId", label: "Permit", type: "select", relation: "permits" },
      baseFields.locationId,
      { name: "inspectorPersonId", label: "Inspector", type: "select", relation: "people" },
      { name: "inspectionDate", label: "Inspection Date", placeholder: "YYYY-MM-DD", required: true },
      { name: "criteriaReference", label: "Criteria / Checklist Reference" },
      { name: "findingIds", label: "Findings", type: "multiselect", relation: "findings" },
      { name: "actionIds", label: "Actions", type: "multiselect", relation: "correctiveActions" },
    ],
  }),
  register({
    kind: "environmental-events",
    collection: "environmentalEvents",
    basePath: "/environment/events",
    breadcrumbs: "Environmental",
    sidebarSection: "environmental",
    sidebarTitle: "Environmental",
    title: "Environmental Events",
    recordLabel: "environmental event",
    pluralRecordLabel: "environmental events",
    summary: "Track spills and releases with source, material, quantity, response, notifications, investigation, actions, and closure.",
    businessPrefix: "EE",
    typeOptions: ["Spill", "Release", "Unauthorized Discharge", "Permit Deviation", "Notification Event", "Other"],
    statusOptions: ["Open", "Contained", "Under Investigation", "Reporting Review", "Action Required", "Closed"],
    defaultType: "Spill",
    defaultStatus: "Open",
    fields: [
      { name: "eventDate", label: "Date and Time", required: true, placeholder: "YYYY-MM-DDTHH:mm" },
      baseFields.locationId,
      { name: "environmentalSourceId", label: "Environmental Source", type: "select", relation: "environmentalSources" },
      baseFields.chemicalId,
      { name: "quantity", label: "Estimated Quantity" },
      { name: "unit", label: "Unit" },
      { name: "mediaAffected", label: "Media Affected" },
      { name: "immediateResponse", label: "Immediate Response", type: "textarea", rows: 3 },
      { name: "notifications", label: "Notifications", type: "textarea", rows: 3 },
      { name: "investigation", label: "Investigation Summary", type: "textarea", rows: 3 },
      { name: "findingIds", label: "Findings", type: "multiselect", relation: "findings" },
      { name: "actionIds", label: "Actions", type: "multiselect", relation: "correctiveActions" },
    ],
  }),
  register({
    kind: "document-references",
    collection: "documentReferences",
    basePath: "/reports/documents",
    breadcrumbs: "Reports",
    sidebarSection: "reports",
    sidebarTitle: "Reports",
    title: "Document References",
    recordLabel: "document reference",
    pluralRecordLabel: "document references",
    summary: "Link operational records to external controlled documents or evidence without making OLUSO a document repository.",
    businessPrefix: "DOC",
    typeOptions: ["SOP", "SDS", "Permit", "Report", "Laboratory Report", "Drawing", "JHA", "Training Evidence", "Inspection Evidence", "Photo Package", "Other"],
    statusOptions: lifecycleStatuses,
    defaultType: "SOP",
    defaultStatus: "Active",
    fields: [
      { name: "documentNumber", label: "Document Number" },
      { name: "revision", label: "Revision" },
      baseFields.owner,
      { name: "effectiveDate", label: "Effective Date", placeholder: "YYYY-MM-DD" },
      baseFields.reviewDate,
      { name: "externalPath", label: "External Path / URL", required: true },
      { name: "sourceSystem", label: "Source System / Repository" },
      { name: "linkedRecordSummary", label: "Linked Record Summary", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "data-quality-findings",
    collection: "dataQualityFindings",
    basePath: "/reports/data-quality",
    breadcrumbs: "Reports",
    sidebarSection: "reports",
    sidebarTitle: "Reports",
    title: "Data Quality Findings",
    recordLabel: "data quality finding",
    pluralRecordLabel: "data quality findings",
    summary: "Track material identity, relationship, vocabulary, evidence, review, export, and migration defects.",
    businessPrefix: "DQ",
    typeOptions: ["Missing Identifier", "Duplicate Identifier", "Missing Relationship", "Orphaned Reference", "Archived Relationship", "Uncontrolled Value", "Missing Evidence", "Expired Review", "Overdue Work", "Migration Blocker"],
    statusOptions: ["Open", "Acknowledged", "In Progress", "Resolved", "Suppressed"],
    defaultType: "Migration Blocker",
    defaultStatus: "Open",
    fields: [
      { name: "severity", label: "Severity", type: "select", required: true, options: ["Critical", "High", "Medium", "Low"] },
      { name: "affectedCollection", label: "Affected Collection" },
      { name: "affectedRecordId", label: "Affected Record ID" },
      { name: "rule", label: "Rule / Check" },
      { name: "remediation", label: "Remediation", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "migration-mappings",
    collection: "migrationMappings",
    basePath: "/reports/migration-mappings",
    breadcrumbs: "Reports",
    sidebarSection: "reports",
    sidebarTitle: "Reports",
    title: "Migration Mappings",
    recordLabel: "migration mapping",
    pluralRecordLabel: "migration mappings",
    summary: "Maintain field-level mapping notes between OLUSO records and future Vitre or other destination schemas.",
    businessPrefix: "MAP",
    typeOptions: ["Entity Mapping", "Field Mapping", "Vocabulary Mapping", "Relationship Mapping", "Transformation"],
    statusOptions: ["Unmapped", "Mapped", "Transformation Required", "Blocked", "Validated", "Migrated"],
    defaultType: "Field Mapping",
    defaultStatus: "Unmapped",
    fields: [
      { name: "olusoEntity", label: "OLUSO Entity", required: true },
      { name: "olusoField", label: "OLUSO Field", required: true },
      { name: "fieldMeaning", label: "Field Meaning", type: "textarea", rows: 3 },
      { name: "dataType", label: "Data Type" },
      { name: "controlledVocabulary", label: "Controlled Vocabulary Source" },
      { name: "destinationSystem", label: "Destination System", defaultValue: "Vitre" },
      { name: "destinationEntity", label: "Destination Entity" },
      { name: "destinationField", label: "Destination Field" },
      { name: "transformationRequired", label: "Transformation Required", type: "checkbox" },
      { name: "relationshipLookupRequired", label: "Relationship Lookup Required", type: "checkbox" },
      { name: "validationResult", label: "Validation Result", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "import-runs",
    collection: "importRuns",
    basePath: "/reports/import-runs",
    breadcrumbs: "Reports",
    sidebarSection: "reports",
    sidebarTitle: "Reports",
    title: "Import Runs",
    recordLabel: "import run",
    pluralRecordLabel: "import runs",
    summary: "Record controlled import previews, validation outcomes, duplicate handling, failures, and summaries.",
    businessPrefix: "IMP",
    typeOptions: ["Master Data CSV", "Register CSV", "Backup Merge", "Dry Run"],
    statusOptions: ["Previewed", "Validated", "Committed", "Rejected", "Failed"],
    defaultType: "Master Data CSV",
    defaultStatus: "Previewed",
    fields: [
      { name: "targetEntity", label: "Target Entity", required: true },
      { name: "sourceReference", label: "Source Reference" },
      { name: "rowCount", label: "Row Count" },
      { name: "validCount", label: "Valid Rows" },
      { name: "failedCount", label: "Failed Rows" },
      { name: "duplicateCount", label: "Duplicate Candidates" },
      { name: "failureSummary", label: "Failure Summary", type: "textarea", rows: 3 },
    ],
  }),
  register({
    kind: "migration-bundles",
    collection: "migrationBundles",
    basePath: "/reports/migration-bundles",
    breadcrumbs: "Reports",
    sidebarSection: "reports",
    sidebarTitle: "Reports",
    title: "Migration Bundles",
    recordLabel: "migration bundle",
    pluralRecordLabel: "migration bundles",
    summary: "Track versioned export bundles, schema context, mapping inclusion, dry-run counts, rejections, and reconciliation.",
    businessPrefix: "BUNDLE",
    typeOptions: ["Full Export", "Delta Export", "Dry Run", "Reconciliation", "Migration Package"],
    statusOptions: ["Draft", "Generated", "Dry Run", "Reconciled", "Blocked", "Validated"],
    defaultType: "Full Export",
    defaultStatus: "Draft",
    fields: [
      { name: "bundleVersion", label: "Bundle Version" },
      { name: "includedCollections", label: "Included Collections", type: "textarea", rows: 3 },
      { name: "schemaVersion", label: "Schema Version" },
      { name: "recordCount", label: "Record Count" },
      { name: "rejectedCount", label: "Rejected Count" },
      { name: "transformationSummary", label: "Transformation Summary", type: "textarea", rows: 3 },
      { name: "reconciliationSummary", label: "Reconciliation Summary", type: "textarea", rows: 3 },
    ],
  }),
] as const satisfies readonly CampaignRegisterDefinition[];

export type CampaignRegisterKind = (typeof CAMPAIGN_REGISTER_DEFINITIONS)[number]["kind"];
export type CampaignCollectionName = (typeof CAMPAIGN_REGISTER_DEFINITIONS)[number]["collection"];

export const CAMPAIGN_COLLECTION_NAMES = CAMPAIGN_REGISTER_DEFINITIONS.map(
  (definition) => definition.collection,
) as CampaignCollectionName[];

export function isCampaignCollectionName(value: string): value is CampaignCollectionName {
  return CAMPAIGN_COLLECTION_NAMES.includes(value as CampaignCollectionName);
}

export function isCampaignRegisterKind(value: string): value is CampaignRegisterKind {
  return CAMPAIGN_REGISTER_DEFINITIONS.some((definition) => definition.kind === value);
}

export function getCampaignRegisterDefinitionByCollection(
  collection: CampaignCollectionName,
): CampaignRegisterDefinition {
  const definition = CAMPAIGN_REGISTER_DEFINITIONS.find((candidate) => candidate.collection === collection);

  if (!definition) {
    throw new Error(`Unknown campaign collection: ${collection}`);
  }

  return definition;
}

export function getCampaignRegisterDefinitionByKind(
  kind: CampaignRegisterKind,
): CampaignRegisterDefinition {
  const definition = CAMPAIGN_REGISTER_DEFINITIONS.find((candidate) => candidate.kind === kind);

  if (!definition) {
    throw new Error(`Unknown campaign register kind: ${kind}`);
  }

  return definition;
}

export const CAMPAIGN_RECORD_EXPORT_COLUMNS = [
  "id",
  "businessId",
  "title",
  "type",
  "status",
  "summary",
  "owner",
  "locationId",
  "processId",
  "personId",
  "organizationId",
  "taskId",
  "segId",
  "chemicalId",
  "equipmentId",
  "hazardIds",
  "controlIds",
  "relatedRecordIds",
  "effectiveFrom",
  "effectiveTo",
  "dueDate",
  "reviewDate",
  "evidenceReference",
  "notes",
  "createdAt",
  "updatedAt",
  "lifecycleStatus",
  "archivedAt",
  "archivedReason",
] as const;
