import type { SidebarConfig, SidebarItem } from "./sidebar.types";
import { CAMPAIGN_REGISTER_DEFINITIONS } from "$lib/persistence/campaign-register.types";

const futureModuleChildren: SidebarItem[] = CAMPAIGN_REGISTER_DEFINITIONS.map((definition) => ({
  id: definition.kind,
  title: definition.title,
  route: definition.basePath,
  icon: "ClipboardList",
  routeType: "register",
  status: "deferred",
  description: `${definition.sidebarTitle}; available for migration/reference review, not a completed Campaign 6 workflow.`,
}));

export const SIDEBAR_CONFIG: SidebarConfig = {
  appTitle: "ADAMA HSE",
  sections: [
    {
      id: "home",
      title: "Home",
      icon: "LayoutDashboard",
      collapsible: false,
      defaultExpanded: true,
      children: [
        {
          id: "home",
          title: "Home",
          route: "/home",
          icon: "LayoutDashboard",
          routeType: "landing",
        },
        {
          id: "global-search",
          title: "Search",
          route: "/search",
          icon: "Search",
          routeType: "landing",
        },
        {
          id: "activity",
          title: "Activity",
          route: "/activity",
          icon: "History",
          routeType: "landing",
          description: "Trace immutable revisions and clearly labeled limited legacy metadata.",
        },
      ],
    },
    {
      id: "operations",
      title: "Operations",
      icon: "Factory",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "actions",
          title: "Actions",
          route: "/actions/corrective-actions",
          icon: "ListChecks",
          routeType: "register",
        },
        {
          id: "inspections-observations",
          title: "Inspections & Observations",
          route: "/field/findings",
          icon: "ClipboardCheck",
          routeType: "register",
        },
        {
          id: "incidents",
          title: "Incidents",
          route: "/incidents/log",
          icon: "TriangleAlert",
          routeType: "register",
        },
      ],
    },
    {
      id: "plant",
      title: "The Plant",
      icon: "MapPinned",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "locations",
          title: "Locations",
          route: "/operations/locations",
          icon: "MapPinned",
          routeType: "register",
        },
        {
          id: "functions-processes-tasks",
          title: "Functions, Processes & Tasks",
          route: "/enterprise/navigator",
          icon: "Workflow",
          routeType: "landing",
        },
        {
          id: "equipment",
          title: "Equipment",
          route: "/operations/equipment",
          icon: "Wrench",
          routeType: "register",
        },
        {
          id: "people",
          title: "People",
          route: "/people/workers",
          icon: "UsersRound",
          routeType: "register",
        },
        {
          id: "chemicals-sds",
          title: "Chemicals & SDS",
          route: "/master/products",
          icon: "FlaskConical",
          routeType: "register",
        },
      ],
    },
    {
      id: "exposure",
      title: "Exposure",
      icon: "ShieldAlert",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "segs",
          title: "Similar Exposure Groups (SEGs)",
          route: "/hse/segs",
          icon: "UsersRound",
          routeType: "register",
        },
        {
          id: "risk-assessments",
          title: "Assessments",
          route: "/risk/assessments",
          icon: "FileBarChart",
          routeType: "register",
        },
        {
          id: "exposure-monitoring",
          title: "Monitoring & Sampling",
          route: "/hse/exposure-monitoring",
          icon: "ClipboardList",
          routeType: "register",
        },
        {
          id: "controls",
          title: "Controls & Reassessment",
          route: "/risk/controls",
          icon: "ShieldCheck",
          routeType: "register",
        },
      ],
    },
    {
      id: "reports",
      title: "Reports",
      icon: "FileBarChart",
      collapsible: false,
      defaultExpanded: true,
      children: [
        {
          id: "exports",
          title: "Review Packets & Exports",
          route: "/reports/exports",
          icon: "FileOutput",
          routeType: "report",
        },
      ],
    },
    {
      id: "administration",
      title: "Administration",
      icon: "Settings",
      collapsible: false,
      defaultExpanded: true,
      children: [
        {
          id: "local-profile",
          title: "Profile & Local Actor",
          route: "/settings/profile",
          icon: "UsersRound",
          routeType: "system",
        },
        {
          id: "installation",
          title: "Installation",
          route: "/settings/installation",
          icon: "Settings",
          routeType: "system",
        },
        {
          id: "settings",
          title: "Storage, Backups & Diagnostics",
          route: "/system/settings",
          icon: "Settings",
          routeType: "system",
        },
      ],
    },
    {
      id: "future-modules",
      title: "Future Modules",
      icon: "ClipboardList",
      collapsible: true,
      defaultExpanded: false,
      children: futureModuleChildren,
    },
  ],
};