import type { SidebarConfig } from "./sidebar.types";
import { CAMPAIGN_REGISTER_DEFINITIONS } from "$lib/persistence/campaign-register.types";

function campaignChildrenFor(sectionId: string, routeType: "register" | "report" = "register") {
  return CAMPAIGN_REGISTER_DEFINITIONS.filter(
    (definition) => definition.sidebarSection === sectionId,
  ).map((definition) => ({
    id: definition.kind,
    title: definition.title,
    route: definition.basePath,
    icon: routeType === "report" ? "FileBarChart" : "ClipboardList",
    routeType,
  }));
}

export const SIDEBAR_CONFIG: SidebarConfig = {
  appTitle: "OLUSO",
  sections: [
    {
      id: "dashboard",
      title: "Dashboard",
      icon: "LayoutDashboard",
      collapsible: false,
      defaultExpanded: true,
      children: [
        {
          id: "dashboard-home",
          title: "Dashboard",
          route: "/dashboard",
          icon: "LayoutDashboard",
          routeType: "landing",
        },
        {
          id: "global-search",
          title: "Global Search",
          route: "/search",
          icon: "Search",
          routeType: "landing",
        },
      ],
    },
    {
      id: "operations",
      title: "Operations",
      icon: "Factory",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "locations",
          title: "Locations",
          route: "/operations/locations",
          icon: "MapPinned",
          routeType: "register",
        },
        {
          id: "processes",
          title: "Processes",
          route: "/operations/processes",
          icon: "Workflow",
          routeType: "register",
        },
        {
          id: "tasks",
          title: "Tasks",
          route: "/operations/tasks",
          icon: "ListChecks",
          routeType: "register",
        },
        {
          id: "equipment",
          title: "Equipment",
          route: "/operations/equipment",
          icon: "Wrench",
          routeType: "register",
        },
        ...campaignChildrenFor("operations"),
      ],
    },
    {
      id: "people-work",
      title: "People & Work",
      icon: "UsersRound",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "organizations",
          title: "Organizations",
          route: "/people/organizations",
          icon: "UsersRound",
          routeType: "register",
        },
        {
          id: "people",
          title: "People",
          route: "/people/workers",
          icon: "UsersRound",
          routeType: "register",
        },
        ...campaignChildrenFor("people-work"),
      ],
    },
    {
      id: "hse-registers",
      title: "HSE Registers",
      icon: "ShieldAlert",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "chemicals",
          title: "Chemicals",
          route: "/hse/chemicals",
          icon: "FlaskConical",
          routeType: "register",
        },
        {
          id: "hazards",
          title: "Hazards",
          route: "/hse/hazards",
          icon: "TriangleAlert",
          routeType: "register",
        },
        {
          id: "segs",
          title: "SEGs",
          route: "/hse/segs",
          icon: "UsersRound",
          routeType: "register",
        },
        {
          id: "exposure-monitoring",
          title: "Exposure Monitoring",
          route: "/hse/exposure-monitoring",
          icon: "FileBarChart",
          routeType: "register",
        },
      ],
    },
    {
      id: "industrial-hygiene",
      title: "Industrial Hygiene",
      icon: "FileBarChart",
      collapsible: true,
      defaultExpanded: false,
      children: campaignChildrenFor("industrial-hygiene"),
    },
    {
      id: "training",
      title: "Training",
      icon: "ClipboardCheck",
      collapsible: true,
      defaultExpanded: false,
      children: campaignChildrenFor("training"),
    },
    {
      id: "risk-management",
      title: "Risk Management",
      icon: "ShieldCheck",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "controls",
          title: "Controls",
          route: "/risk/controls",
          icon: "ShieldCheck",
          routeType: "register",
        },
        {
          id: "risk-assessments",
          title: "Risk Assessments",
          route: "/risk/assessments",
          icon: "FileBarChart",
          routeType: "register",
        },
      ],
    },
    {
      id: "field-work",
      title: "Field Work",
      icon: "ClipboardCheck",
      collapsible: true,
      defaultExpanded: false,
      children: [
        {
          id: "findings",
          title: "Findings",
          route: "/field/findings",
          icon: "ClipboardList",
          routeType: "register",
        },
        ...campaignChildrenFor("field-work"),
      ],
    },
    {
      id: "change-control",
      title: "Change Control",
      icon: "Workflow",
      collapsible: true,
      defaultExpanded: false,
      children: campaignChildrenFor("change-control"),
    },
    {
      id: "actions",
      title: "Actions",
      icon: "CheckSquare",
      collapsible: true,
      defaultExpanded: true,
      children: [
        {
          id: "corrective-actions",
          title: "Corrective Actions",
          route: "/actions/corrective-actions",
          icon: "ListChecks",
          routeType: "register",
        },
      ],
    },
    {
      id: "incidents",
      title: "Incidents",
      icon: "TriangleAlert",
      collapsible: true,
      defaultExpanded: false,
      children: [
        {
          id: "incident-log",
          title: "Incidents & Near Misses",
          route: "/incidents/log",
          icon: "TriangleAlert",
          routeType: "register",
        },
      ],
    },
    {
      id: "compliance",
      title: "Compliance",
      icon: "ClipboardCheck",
      collapsible: true,
      defaultExpanded: false,
      children: [
        {
          id: "compliance-items",
          title: "Compliance Support",
          route: "/compliance/items",
          icon: "ClipboardCheck",
          routeType: "register",
        },
      ],
    },
    {
      id: "environmental",
      title: "Environmental",
      icon: "ShieldAlert",
      collapsible: true,
      defaultExpanded: false,
      children: campaignChildrenFor("environmental"),
    },
    {
      id: "reports",
      title: "Reports",
      icon: "FileBarChart",
      collapsible: true,
      defaultExpanded: false,
      children: [
        {
          id: "exports",
          title: "Exports",
          route: "/reports/exports",
          icon: "FileOutput",
          routeType: "report",
        },
        ...campaignChildrenFor("reports", "report"),
      ],
    },
    {
      id: "system",
      title: "System",
      icon: "Settings",
      collapsible: true,
      defaultExpanded: false,
      children: [
        {
          id: "settings",
          title: "Settings",
          route: "/system/settings",
          icon: "Settings",
          routeType: "system",
        },
      ],
    },
  ],
};
